export const hcps=[
{id:"hcp-001",name:"Dr Ananya Mehta",specialty:"Endocrinology",city:"Mumbai",institution:"Western Metabolic Institute",credentials:"MBBS, MD, DM",registry:"DMC 48291",verification:"VERIFIED",focus:"Obesity phenotyping, diabetes remission and GLP-1 transition care",peerAuthority:93,clinicalRelevance:91,networkReach:72,recency:94,movement:4.2},
{id:"hcp-002",name:"Dr Rohan Iyer",specialty:"Bariatric surgery",city:"Bengaluru",institution:"South India Obesity Centre",credentials:"MBBS, MS, FNB",registry:"KMC 22184",verification:"VERIFIED",focus:"Bariatric outcomes and multidisciplinary treatment selection",peerAuthority:85,clinicalRelevance:88,networkReach:61,recency:86,movement:1.8},
{id:"hcp-003",name:"Dr Farah Khan",specialty:"Diabetology",city:"Hyderabad",institution:"Deccan Diabetes Collaborative",credentials:"MBBS, MD",registry:"TSMC 77421",verification:"VERIFIED",focus:"South Asian cardiometabolic risk and access to incretin therapy",peerAuthority:79,clinicalRelevance:93,networkReach:78,recency:91,movement:6.1},
{id:"hcp-004",name:"Dr Karthik Menon",specialty:"Internal medicine",city:"Chennai",institution:"Chennai Integrated Care",credentials:"MBBS, MD, DNB",registry:"TNMC 55910",verification:"REVIEW",focus:"Primary care risk stratification and obesity referral pathways",peerAuthority:67,clinicalRelevance:79,networkReach:49,recency:75,movement:-1.3},
{id:"hcp-005",name:"Dr Nisha Banerjee",specialty:"Endocrinology",city:"Kolkata",institution:"Eastern Institute of Endocrinology",credentials:"MBBS, MD, DM",registry:"WBMC 33720",verification:"VERIFIED",focus:"Guideline synthesis and women's metabolic health",peerAuthority:76,clinicalRelevance:85,networkReach:58,recency:82,movement:2.7},
{id:"hcp-006",name:"Dr Vivek Rao",specialty:"Metabolic medicine",city:"New Delhi",institution:"Capital Metabolic Clinic",credentials:"MBBS, MD, MRCP",registry:"DMC 70944",verification:"VERIFIED",focus:"Obesity stigma, treatment persistence and patient education",peerAuthority:72,clinicalRelevance:84,networkReach:88,recency:90,movement:5.4}];
export const evidence=[
{id:"ev-1001",hcpId:"hcp-001",sourceType:"Peer-reviewed",source:"Indian Journal of Endocrinology",publishedAt:"2026-09-18",ingestedAt:"2026-09-23T10:40:00Z",claim:"Body composition and comorbidity burden should complement BMI when assessing obesity in Asian Indian adults.",topic:"Diagnosis",stance:"BALANCED",quality:94,extraction:"Author statement",disposition:"ACCEPTED",url:"https://example.org/evidence/1001"},
{id:"ev-1002",hcpId:"hcp-003",sourceType:"Congress",source:"RSSDI regional forum",publishedAt:"2026-09-21",ingestedAt:"2026-09-23T11:12:00Z",claim:"Affordability may expand incretin access, but structured follow-up is necessary to reduce discontinuation and inappropriate use.",topic:"Access",stance:"BALANCED",quality:81,extraction:"Transcript extract",disposition:"ACCEPTED",url:"https://example.org/evidence/1002"},
{id:"ev-1003",hcpId:"hcp-006",sourceType:"Social",source:"Public professional profile",publishedAt:"2026-09-22",ingestedAt:"2026-09-23T11:36:00Z",claim:"Weight recurrence after stopping therapy should be discussed before treatment begins.",topic:"Persistence",stance:"CAUTION",quality:66,extraction:"Model-assisted quote",disposition:"REVIEW",url:"https://example.org/evidence/1003"},
{id:"ev-1004",hcpId:"hcp-002",sourceType:"Peer-reviewed",source:"Obesity Surgery India",publishedAt:"2026-09-11",ingestedAt:"2026-09-22T07:10:00Z",claim:"Treatment selection should be multidisciplinary and based on disease severity, complications and patient preference.",topic:"Care pathway",stance:"SUPPORTIVE",quality:91,extraction:"Abstract conclusion",disposition:"ACCEPTED",url:"https://example.org/evidence/1004"},
{id:"ev-1005",hcpId:"hcp-005",sourceType:"Guideline",source:"Specialty consensus update",publishedAt:"2026-09-09",ingestedAt:"2026-09-21T05:42:00Z",claim:"Nutritional adequacy and preservation of lean mass require active monitoring during pharmacological weight loss.",topic:"Safety",stance:"CAUTION",quality:96,extraction:"Recommendation",disposition:"ACCEPTED",url:"https://example.org/evidence/1005"},
{id:"ev-1006",hcpId:"hcp-004",sourceType:"News",source:"Clinical practice interview",publishedAt:"2026-09-20",ingestedAt:"2026-09-22T08:15:00Z",claim:"Earlier referral from primary care could reduce delays in treating obesity-related complications.",topic:"Referral",stance:"SUPPORTIVE",quality:59,extraction:"Attributed quote",disposition:"REVIEW",url:"https://example.org/evidence/1006"},
{id:"ev-1007",hcpId:"hcp-001",sourceType:"Guideline",source:"National obesity practice update",publishedAt:"2026-08-28",ingestedAt:"2026-09-18T08:15:00Z",claim:"Long-term obesity care requires shared goals, periodic response assessment and explicit stopping rules.",topic:"Care pathway",stance:"SUPPORTIVE",quality:98,extraction:"Recommendation",disposition:"ACCEPTED",url:"https://example.org/evidence/1007"}];
export const safetyCases=[
{id:"PV-2048",hcpId:"hcp-003",status:"SCREENED",priority:"CRITICAL",product:"Semaglutide",event:"Acute pancreatitis",soc:"Gastrointestinal disorders",hoursRemaining:5,criteria:{patient:true,reporter:true,product:true,event:true},excerpt:"A patient receiving semaglutide developed acute pancreatitis following dose escalation. Timing and reporter contact are present; identifiers are withheld from this workspace.",updatedAt:"2026-09-24T06:25:00Z"},
{id:"PV-2052",hcpId:"hcp-001",status:"VALIDATED",priority:"WATCH",product:"Tirzepatide",event:"Persistent nausea",soc:"Gastrointestinal disorders",hoursRemaining:13,criteria:{patient:true,reporter:true,product:true,event:true},excerpt:"Persistent nausea led to discontinuation. Concomitant medication detail requires medical review before any reporting decision.",updatedAt:"2026-09-24T04:08:00Z"},
{id:"PV-2056",hcpId:"hcp-006",status:"SCREENED",priority:"WATCH",product:"Liraglutide",event:"Hypoglycaemia",soc:"Metabolism and nutrition disorders",hoursRemaining:21,criteria:{patient:true,reporter:false,product:true,event:true},excerpt:"Hypoglycaemia was mentioned in combination-therapy context. A contactable reporter is not yet established.",updatedAt:"2026-09-24T02:46:00Z"}];
export const audits=[{at:"2026-09-24T07:10:00Z",actor:"Scoring service",action:"Recomputed influence model 2.3",record:"6 profiles"},{at:"2026-09-24T06:42:00Z",actor:"Evidence reviewer",action:"Accepted guideline recommendation",record:"ev-1005"},{at:"2026-09-24T06:25:00Z",actor:"PV classifier",action:"Created screened potential case",record:"PV-2048"},{at:"2026-09-24T05:58:00Z",actor:"Identity resolver",action:"Held profile for registry review",record:"hcp-004"}];

export const researchProfiles=[
{id:"kol-anoop-misra",name:"Prof Anoop Misra",specialty:"Endocrinology and metabolic medicine",city:"New Delhi",affiliation:"Fortis C-DOC; N-DOC; Diabetes Foundation India",matchConfidence:99,aliases:["Anoop Misra","Prof (Dr) Anoop Misra"],footprints:[
{id:"src-am-1",type:"INSTITUTION",title:"Executive Chairman, Fortis C-DOC",summary:"Fortis identifies Misra as Executive Chairman of Fortis C-DOC and links him to N-DOC and Diabetes Foundation India.",publisher:"Fortis Healthcare",date:"Current profile",confidence:"VERIFIED",url:"https://www.fortishealthcare.com/doctors/dr-anoop-misra-2205"},
{id:"src-am-2",type:"PUBLICATION",title:"Revised definition of obesity in Asian Indians living in India",summary:"Lead-author publication defining staged obesity for Asian Indians; PubMed supplies authors, affiliations, DOI and conflict-of-interest disclosures.",publisher:"PubMed / Diabetes & Metabolic Syndrome",date:"15 Jan 2025",confidence:"VERIFIED",url:"https://pubmed.ncbi.nlm.nih.gov/39814628/"},
{id:"src-am-3",type:"SOCIAL",title:"Public professional activity on paediatric obesity and metabolic health",summary:"The identity-resolved LinkedIn profile shows current posts discussing semaglutide in paediatric obesity, metabolic monitoring and an AIIMS obesity summit oration.",publisher:"LinkedIn",date:"Observed Sep 2026",confidence:"VERIFIED",url:"https://in.linkedin.com/in/anoop-misra-323b0656"}]},
{id:"kol-shashank-joshi",name:"Prof Shashank R Joshi",specialty:"Endocrinology",city:"Mumbai",affiliation:"Sir H. N. Reliance Foundation Hospital",matchConfidence:99,aliases:["Shashank Joshi","Shashank R. Joshi"],footprints:[
{id:"src-sj-1",type:"INSTITUTION",title:"Consultant, Department of Endocrinology",summary:"The hospital profile verifies qualifications, current consultant role, obesity research focus, society leadership and an extensive publication record.",publisher:"Sir H. N. Reliance Foundation Hospital",date:"Current profile",confidence:"VERIFIED",url:"https://www.rfhospital.org/about-us/doctors-directory/shashank-r-joshi"},
{id:"src-sj-2",type:"CONFERENCE",title:"RSSDI 2024 obesity masterclass faculty and moderator",summary:"The official scientific programme lists Joshi as chair, speaker on SURMOUNT 1 and 2, panel participant and moderator in the obesity masterclass.",publisher:"RSSDI 2024 Scientific Programme",date:"16 Nov 2024",confidence:"VERIFIED",url:"https://rssdi2024delhi.com/pdf/rssdi-2024-scientific-program.pdf"},
{id:"src-sj-3",type:"SOCIAL",title:"Identity-matched public professional profile",summary:"The LinkedIn profile matches Mumbai, Lilavati Hospital, KEM education and Indian Academy of Diabetes leadership signals.",publisher:"LinkedIn",date:"Current profile",confidence:"VERIFIED",url:"https://in.linkedin.com/in/shashank-joshi-75a19a93"}]},
{id:"kol-nitin-kapoor",name:"Prof Nitin Kapoor",specialty:"Endocrinology and bariatric medicine",city:"Vellore",affiliation:"Christian Medical College Vellore",matchConfidence:99,aliases:["Nitin Kapoor","Dr Nitin Kapoor"],footprints:[
{id:"src-nk-1",type:"INSTITUTION",title:"Professor and Head, Unit I; Consultant Endocrinologist and Bariatric Physician",summary:"CMC's faculty profile verifies training, present role, obesity research focus, editorial positions and society roles.",publisher:"CMC Vellore",date:"Current profile",confidence:"VERIFIED",url:"https://www.cmcendovellore.org/nitin-kapoor-php/"},
{id:"src-nk-2",type:"PUBLICATION",title:"Normal Weight Obesity: An Underrecognized Problem in Individuals of South Asian Descent",summary:"The hosted paper verifies authorship and CMC Vellore affiliation and frames normal-weight obesity as a South Asian phenotype.",publisher:"Clinical Therapeutics / CMC Vellore",date:"2019",confidence:"VERIFIED",url:"https://www.cmcendovellore.org/wp-content/uploads/2020/10/9-2019-Normal-weight-obesity-An-under-recognized-problem-in-individuals-of-South-Asian-descent.pdf"},
{id:"src-nk-3",type:"CONFERENCE",title:"Knowledge, Attitude, and Practice of Individuals with Obesity",summary:"CMC's publication index records Kapoor and co-authors against ADA abstract DOI 10.2337/db24-74-PUB. Classed as an abstract/poster record pending programme-page confirmation.",publisher:"ADA abstract record / CMC Vellore",date:"2024",confidence:"REVIEW",url:"https://www.cmcendovellore.org/publications/knowledge-attitude-and-practice-of-individuals-with-obesity/"},
{id:"src-nk-4",type:"SOCIAL",title:"Public professional activity on muscle and metabolic health",summary:"The identity-matched LinkedIn profile shows current discussion of muscle loss, rapid weight loss and obesity as an endocrine disease.",publisher:"LinkedIn",date:"Observed Sep 2026",confidence:"VERIFIED",url:"https://in.linkedin.com/in/nitin-kapoor-endocrine"}]},
{id:"kol-ambrish-mithal",name:"Dr Ambrish Mithal",specialty:"Endocrinology and diabetes",city:"New Delhi",affiliation:"Max Healthcare, Saket",matchConfidence:99,aliases:["Ambrish Mithal","Dr. Ambrish Mithal"],footprints:[
{id:"src-mm-1",type:"INSTITUTION",title:"Chairman and Head, Endocrinology and Diabetes",summary:"Max Healthcare verifies Mithal's current role, prior Medanta tenure, qualifications, memberships and specialty interests.",publisher:"Max Healthcare",date:"Current profile",confidence:"VERIFIED",url:"https://www.maxhealthcare.in/international/en/doctor/dr-ambrish-mithal"},
{id:"src-mm-2",type:"CONFERENCE",title:"Faculty: Utility of GLP-1 receptor agonists beyond diabetes",summary:"The IDSI scientific programme lists Mithal as faculty for a session on GLP-1 receptor agonists beyond diabetes.",publisher:"IDSI scientific programme",date:"2023",confidence:"VERIFIED",url:"https://idsi.s3.ap-south-1.amazonaws.com/idsi.in/scientific_programs/2023.pdf"}]}
];
