import { attachDiscoveredFootprints } from './source-library.mjs';
export const hcps=[];
export const evidence=[];
export const safetyCases=[];
export const audits=[];

export const socialAccounts=[
{id:"social-am-x",hcpId:"kol-anoop-misra",platform:"X",handle:"@docanoopmisra",profileUrl:"https://x.com/docanoopmisra",identityStatus:"VERIFIED",collectionStatus:"CONNECTOR_REQUIRED",lastCheckedAt:"2026-09-24T12:00:00.000Z",source:"Public profile"},
{id:"social-sj-x",hcpId:"kol-shashank-joshi",platform:"X",handle:"@AskDrShashank",profileUrl:"https://x.com/AskDrShashank",identityStatus:"VERIFIED",collectionStatus:"CONNECTOR_REQUIRED",lastCheckedAt:"2026-09-24T12:00:00.000Z",source:"Public profile"},
{id:"social-mm-x",hcpId:"kol-ambrish-mithal",platform:"X",handle:"@DrAmbrishMithal",profileUrl:"https://x.com/DrAmbrishMithal",identityStatus:"VERIFIED",collectionStatus:"CONNECTOR_REQUIRED",lastCheckedAt:"2026-09-24T12:00:00.000Z",source:"Public profile"},
{id:"social-vm-yt",hcpId:"kol-v-mohan",platform:"YouTube",handle:"Dr V Mohan",profileUrl:"https://www.youtube.com/@DrVMohan",identityStatus:"VERIFIED",collectionStatus:"PUBLIC_OBSERVATION",lastCheckedAt:"2026-09-24T12:00:00.000Z",source:"Public video and channel"}
];

export const socialPosts=[
{id:"yt-l5qIcj-RylA",accountId:"social-vm-yt",hcpId:"kol-v-mohan",platform:"YouTube",postType:"VIDEO",title:"Public diabetes diet education video",publishedAt:null,capturedAt:"2026-09-24T12:00:00.000Z",url:"https://www.youtube.com/watch?v=l5qIcj-RylA",topics:["Diabetes education","Nutrition"],metrics:{views:3200000,likes:55000,comments:null,reposts:null},metricStatus:"OBSERVED_APPROXIMATE",reviewStatus:"VERIFIED",provenance:"Public YouTube video page; values recorded as approximate at capture time"}
];

export const researchProfiles=[
{id:"kol-anoop-misra",name:"Prof Anoop Misra",specialty:"Endocrinology and metabolic medicine",city:"New Delhi",state:"Delhi",region:"North",affiliation:"Fortis C-DOC; N-DOC; Diabetes Foundation India",tier:"National KOL",matchConfidence:99,aliases:["Anoop Misra","Prof (Dr) Anoop Misra"],footprints:[
{id:"src-am-1",type:"INSTITUTION",title:"Executive Chairman, Fortis C-DOC",summary:"Fortis identifies Misra as Executive Chairman of Fortis C-DOC and links him to N-DOC and Diabetes Foundation India.",publisher:"Fortis Healthcare",date:"Current profile",confidence:"VERIFIED",url:"https://www.fortishealthcare.com/doctors/dr-anoop-misra-2205"},
{id:"src-am-2",type:"PUBLICATION",title:"Revised definition of obesity in Asian Indians living in India",summary:"Lead-author publication defining staged obesity for Asian Indians; PubMed supplies authors, affiliations, DOI and conflict-of-interest disclosures.",publisher:"PubMed / Diabetes & Metabolic Syndrome",date:"15 Jan 2025",confidence:"VERIFIED",url:"https://pubmed.ncbi.nlm.nih.gov/39814628/"},
{id:"src-am-3",type:"SOCIAL",title:"Public professional activity on paediatric obesity and metabolic health",summary:"The identity-resolved LinkedIn profile shows current posts discussing semaglutide in paediatric obesity, metabolic monitoring and an AIIMS obesity summit oration.",publisher:"LinkedIn",date:"Observed Sep 2026",confidence:"VERIFIED",url:"https://in.linkedin.com/in/anoop-misra-323b0656"},
{id:"src-am-4",type:"SOCIAL",title:"Public X profile: @docanoopmisra",summary:"The public profile identifies Fortis C-DOC, former AIIMS faculty status and diabetes and metabolic research activity.",publisher:"X",date:"Current profile",confidence:"VERIFIED",url:"https://x.com/docanoopmisra"},
{id:"src-am-5",type:"NEWS",title:"Doctors urge restrictions on junk-food advertising",summary:"National news coverage names Misra among experts advocating warning labels and restrictions on unhealthy-food promotion.",publisher:"The New Indian Express",date:"10 Aug 2026",confidence:"VERIFIED",url:"https://www.newindianexpress.com/lifestyle/health/2026/Aug/10/leading-indian-doctors-urge-government-to-ban-junk-food-advertising-add-warning-labels"},
{id:"src-am-6",type:"PUBLICATION",title:"Nutritional considerations for glucagon-like peptide-based therapies",summary:"PubMed verifies Misra as a co-author of the 2026 Asian Indian consensus recommendation on nutrition during GLP-based therapy.",publisher:"PubMed / Obesity Pillars",date:"Sep 2026",confidence:"VERIFIED",url:"https://pubmed.ncbi.nlm.nih.gov/42529748/"}]},
{id:"kol-shashank-joshi",name:"Prof Shashank R Joshi",specialty:"Endocrinology",city:"Mumbai",state:"Maharashtra",region:"West",affiliation:"Sir H. N. Reliance Foundation Hospital",tier:"National KOL",matchConfidence:99,aliases:["Shashank Joshi","Shashank R. Joshi"],footprints:[
{id:"src-sj-1",type:"INSTITUTION",title:"Consultant, Department of Endocrinology",summary:"The hospital profile verifies qualifications, current consultant role, obesity research focus, society leadership and an extensive publication record.",publisher:"Sir H. N. Reliance Foundation Hospital",date:"Current profile",confidence:"VERIFIED",url:"https://www.rfhospital.org/about-us/doctors-directory/shashank-r-joshi"},
{id:"src-sj-2",type:"CONFERENCE",title:"RSSDI 2024 obesity masterclass faculty and moderator",summary:"The official scientific programme lists Joshi as chair, speaker on SURMOUNT 1 and 2, panel participant and moderator in the obesity masterclass.",publisher:"RSSDI 2024 Scientific Programme",date:"16 Nov 2024",confidence:"VERIFIED",url:"https://rssdi2024delhi.com/pdf/rssdi-2024-scientific-program.pdf"},
{id:"src-sj-3",type:"SOCIAL",title:"Identity-matched public professional profile",summary:"The LinkedIn profile matches Mumbai, Lilavati Hospital, KEM education and Indian Academy of Diabetes leadership signals.",publisher:"LinkedIn",date:"Current profile",confidence:"VERIFIED",url:"https://in.linkedin.com/in/shashank-joshi-75a19a93"},
{id:"src-sj-4",type:"SOCIAL",title:"Public X profile: @AskDrShashank",summary:"The indexed X profile is identity-matched to Shashank Joshi and provides a public channel for professional posts and replies.",publisher:"X",date:"Current profile",confidence:"VERIFIED",url:"https://x.com/AskDrShashank/with_replies"},
{id:"src-sj-5",type:"PROMOTION",title:"Quoted in oral semaglutide product-launch coverage",summary:"A newspaper launch report quotes Joshi on oral GLP-1 therapy. Classified as promotional context rather than independent editorial opinion.",publisher:"The Indian Express",date:"20 Jan 2022",confidence:"VERIFIED",url:"https://indianexpress.com/article/cities/pune/pharma-launches-anti-diabetic-drug-semaglutide-in-game-changing-pill-form-7733862/"},
{id:"src-sj-6",type:"NEWS",title:"Doctors urge restrictions on junk-food advertising",summary:"National news coverage names Joshi among experts advocating warning labels and restrictions on unhealthy-food promotion.",publisher:"The New Indian Express",date:"10 Aug 2026",confidence:"VERIFIED",url:"https://www.newindianexpress.com/lifestyle/health/2026/Aug/10/leading-indian-doctors-urge-government-to-ban-junk-food-advertising-add-warning-labels"},
{id:"src-sj-7",type:"PUBLICATION",title:"Nutritional considerations for glucagon-like peptide-based therapies",summary:"PubMed lists Joshi as lead author of the 2026 Asian Indian consensus recommendation on nutrition during GLP-based therapy.",publisher:"PubMed / Obesity Pillars",date:"Sep 2026",confidence:"VERIFIED",url:"https://pubmed.ncbi.nlm.nih.gov/42529748/"},
{id:"src-sj-8",type:"CONFERENCE",title:"Metabolically Normal Obesity: Does it exist?",summary:"The official ESICON 2026 scientific programme lists Joshi as the scheduled speaker in the special symposium on controversies in obesity.",publisher:"ESICON 2026 Scientific Programme",date:"Scheduled 22 Oct 2026",confidence:"VERIFIED",url:"https://www.esicon2026.com/scientific_programme.php"}]},
{id:"kol-nitin-kapoor",name:"Prof Nitin Kapoor",specialty:"Endocrinology and bariatric medicine",city:"Vellore",state:"Tamil Nadu",region:"South",affiliation:"Christian Medical College Vellore",tier:"Scientific Leader",matchConfidence:99,aliases:["Nitin Kapoor","Dr Nitin Kapoor"],footprints:[
{id:"src-nk-1",type:"INSTITUTION",title:"Professor and Head, Unit I; Consultant Endocrinologist and Bariatric Physician",summary:"CMC's faculty profile verifies training, present role, obesity research focus, editorial positions and society roles.",publisher:"CMC Vellore",date:"Current profile",confidence:"VERIFIED",url:"https://www.cmcendovellore.org/nitin-kapoor-php/"},
{id:"src-nk-2",type:"PUBLICATION",title:"Normal Weight Obesity: An Underrecognized Problem in Individuals of South Asian Descent",summary:"The hosted paper verifies authorship and CMC Vellore affiliation and frames normal-weight obesity as a South Asian phenotype.",publisher:"Clinical Therapeutics / CMC Vellore",date:"2019",confidence:"VERIFIED",url:"https://www.cmcendovellore.org/wp-content/uploads/2020/10/9-2019-Normal-weight-obesity-An-under-recognized-problem-in-individuals-of-South-Asian-descent.pdf"},
{id:"src-nk-3",type:"CONFERENCE",title:"Knowledge, Attitude, and Practice of Individuals with Obesity",summary:"CMC's publication index records Kapoor and co-authors against ADA abstract DOI 10.2337/db24-74-PUB. Classed as an abstract/poster record pending programme-page confirmation.",publisher:"ADA abstract record / CMC Vellore",date:"2024",confidence:"REVIEW",url:"https://www.cmcendovellore.org/publications/knowledge-attitude-and-practice-of-individuals-with-obesity/"},
{id:"src-nk-4",type:"SOCIAL",title:"Public professional activity on muscle and metabolic health",summary:"The identity-matched LinkedIn profile shows current discussion of muscle loss, rapid weight loss and obesity as an endocrine disease.",publisher:"LinkedIn",date:"Observed Sep 2026",confidence:"VERIFIED",url:"https://in.linkedin.com/in/nitin-kapoor-endocrine"},
{id:"src-nk-5",type:"PUBLICATION",title:"ESI Clinical Practice Guidelines for the Evaluation and Management of Obesity in India - An Update (2025)",summary:"PubMed verifies Kapoor as a co-author of the Endocrine Society of India obesity guideline update and confirms his CMC Vellore endocrinology affiliation.",publisher:"PubMed / Indian Journal of Endocrinology and Metabolism",date:"26 Aug 2025",confidence:"VERIFIED",url:"https://pubmed.ncbi.nlm.nih.gov/40917319/"},
{id:"src-nk-6",type:"PUBLICATION",title:"Burden of Obesity in India: Need for Policy Changes",summary:"The 2026 Clinical Obesity policy paper lists Kapoor among a multi-specialty Indian author group and confirms his CMC Vellore affiliation.",publisher:"PubMed / Clinical Obesity",date:"Apr 2026",confidence:"VERIFIED",url:"https://pubmed.ncbi.nlm.nih.gov/41630400/"}]},
{id:"kol-ambrish-mithal",name:"Dr Ambrish Mithal",specialty:"Endocrinology and diabetes",city:"New Delhi",state:"Delhi",region:"North",affiliation:"Max Healthcare, Saket",tier:"National KOL",matchConfidence:99,aliases:["Ambrish Mithal","Dr. Ambrish Mithal"],footprints:[
{id:"src-mm-1",type:"INSTITUTION",title:"Chairman and Head, Endocrinology and Diabetes",summary:"Max Healthcare verifies Mithal's current role, prior Medanta tenure, qualifications, memberships and specialty interests.",publisher:"Max Healthcare",date:"Current profile",confidence:"VERIFIED",url:"https://www.maxhealthcare.in/international/en/doctor/dr-ambrish-mithal"},
{id:"src-mm-2",type:"CONFERENCE",title:"Faculty: Utility of GLP-1 receptor agonists beyond diabetes",summary:"The IDSI scientific programme lists Mithal as faculty for a session on GLP-1 receptor agonists beyond diabetes.",publisher:"IDSI scientific programme",date:"2023",confidence:"VERIFIED",url:"https://idsi.s3.ap-south-1.amazonaws.com/idsi.in/scientific_programs/2023.pdf"},
{id:"src-mm-3",type:"SOCIAL",title:"Public X profile: @DrAmbrishMithal",summary:"The indexed X profile is identity-matched to Ambrish Mithal and provides a public professional activity channel.",publisher:"X",date:"Current profile",confidence:"VERIFIED",url:"https://x.com/DrAmbrishMithal/with_replies"},
{id:"src-mm-4",type:"NEWS",title:"Doctors urge restrictions on junk-food advertising",summary:"National news coverage names Mithal among experts advocating warning labels and restrictions on unhealthy-food promotion.",publisher:"The New Indian Express",date:"10 Aug 2026",confidence:"VERIFIED",url:"https://www.newindianexpress.com/lifestyle/health/2026/Aug/10/leading-indian-doctors-urge-government-to-ban-junk-food-advertising-add-warning-labels"},
{id:"src-mm-5",type:"PUBLICATION",title:"Nutritional considerations for glucagon-like peptide-based therapies",summary:"PubMed verifies Mithal as a co-author of the 2026 Asian Indian consensus recommendation on nutrition during GLP-based therapy.",publisher:"PubMed / Obesity Pillars",date:"Sep 2026",confidence:"VERIFIED",url:"https://pubmed.ncbi.nlm.nih.gov/42529748/"}]},
{id:"kol-v-mohan",name:"Dr V Mohan",specialty:"Diabetology and metabolic medicine",city:"Chennai",state:"Tamil Nadu",region:"South",affiliation:"Dr Mohan's Diabetes Specialities Centre",tier:"National KOL",matchConfidence:99,aliases:["V Mohan","Viswanathan Mohan","Dr. V. Mohan"],footprints:[
{id:"src-vm-1",type:"INSTITUTION",title:"Chairman and Chief of Diabetology",summary:"The official centre profile identifies Mohan as chairman and chief of diabetology and describes the centre's multi-city diabetes network and research activity.",publisher:"Dr Mohan's Diabetes Specialities Centre",date:"Current profile",confidence:"VERIFIED",url:"https://drmohans.com/doctors/dr-v-mohan/"},
{id:"src-vm-2",type:"PUBLICATION",title:"Clinical and population research profile",summary:"The official professional profile documents extensive diabetes and metabolic research, publications and national scientific leadership.",publisher:"Official profile",date:"Current profile",confidence:"VERIFIED",url:"https://drvmohan.com/"},
{id:"src-vm-3",type:"VIDEO",title:"Public YouTube channel and diabetes education activity",summary:"The verified public video record reports approximately 333,000 followers; a diet education video has more than 3.2 million views and 55,000 likes.",publisher:"YouTube",date:"Observed Sep 2026",confidence:"VERIFIED",url:"https://www.youtube.com/watch?v=l5qIcj-RylA"},
{id:"src-vm-4",type:"PROMOTION",title:"Quoted in oral semaglutide product-launch coverage",summary:"A newspaper launch report quotes Mohan on diabetes, obesity and oral GLP-1 therapy. Classified as promotional context rather than independent editorial opinion.",publisher:"The Indian Express",date:"20 Jan 2022",confidence:"VERIFIED",url:"https://indianexpress.com/article/cities/pune/pharma-launches-anti-diabetic-drug-semaglutide-in-game-changing-pill-form-7733862/"},
{id:"src-vm-5",type:"NEWS",title:"Doctors urge restrictions on junk-food advertising",summary:"National news coverage names Mohan among experts advocating warning labels and restrictions on unhealthy-food promotion.",publisher:"The New Indian Express",date:"10 Aug 2026",confidence:"VERIFIED",url:"https://www.newindianexpress.com/lifestyle/health/2026/Aug/10/leading-indian-doctors-urge-government-to-ban-junk-food-advertising-add-warning-labels"},
{id:"src-vm-6",type:"PUBLICATION",title:"Nutritional considerations for glucagon-like peptide-based therapies",summary:"PubMed verifies Mohan as a co-author of the 2026 Asian Indian consensus recommendation on nutrition during GLP-based therapy for type 2 diabetes and obesity.",publisher:"PubMed / Obesity Pillars",date:"Sep 2026",confidence:"VERIFIED",url:"https://pubmed.ncbi.nlm.nih.gov/42529748/"}]},
{id:"kol-banshi-saboo",name:"Dr Banshi Saboo",specialty:"Diabetology and endocrinology",city:"Ahmedabad",state:"Gujarat",region:"West",affiliation:"Dia Care Diabetes Care & Hormone Clinic",tier:"Regional KOL",matchConfidence:98,aliases:["Banshi Saboo","Dr. Banshi Saboo"],footprints:[
{id:"src-bs-1",type:"INSTITUTION",title:"Consultant diabetologist and clinic founder",summary:"The official profile places Saboo at Dia Care in Ahmedabad and documents diabetes, endocrine and scientific activity.",publisher:"Official professional site",date:"Current profile",confidence:"VERIFIED",url:"https://www.drbanshisaboo.com/"},
{id:"src-bs-2",type:"CONFERENCE",title:"Organising chair, DIAcareCON",summary:"The official scientific agenda identifies Saboo as organising chair and records his role across the meeting programme.",publisher:"DIAcareCON",date:"2023",confidence:"VERIFIED",url:"https://www.diacarecon.co.in/wp-content/uploads/2023/09/DIAcareCON-2023_Scientific-Agenda_Print_compressed.pdf"},
{id:"src-bs-3",type:"PUBLICATION",title:"Nutritional considerations for glucagon-like peptide-based therapies",summary:"PubMed verifies Saboo as a co-author of the 2026 Asian Indian consensus recommendation on nutrition during GLP-based therapy.",publisher:"PubMed / Obesity Pillars",date:"Sep 2026",confidence:"VERIFIED",url:"https://pubmed.ncbi.nlm.nih.gov/42529748/"}]},
{id:"kol-sanjay-kalra",name:"Dr Sanjay Kalra",specialty:"Endocrinology and diabetes",city:"Karnal",state:"Haryana",region:"North",affiliation:"Bharti Hospital",tier:"Scientific Leader",matchConfidence:98,aliases:["Sanjay Kalra","Dr. Sanjay Kalra"],footprints:[
{id:"src-sk-1",type:"INSTITUTION",title:"Consultant endocrinologist, Bharti Hospital",summary:"The professional faculty profile identifies Kalra as an endocrinologist at Bharti Hospital, Karnal and records national and South Asian endocrine leadership roles.",publisher:"CES Faculty",date:"Current profile",confidence:"VERIFIED",url:"https://ces.edu.gh/facilitators/view/dr-sanjay-kalra"},
{id:"src-sk-2",type:"PUBLICATION",title:"Obesity-focused editorial authorship",summary:"The journal record links Kalra to Bharti Hospital's endocrinology department in Karnal and documents obesity-focused scientific authorship.",publisher:"Asian Journal of Diabetology",date:"2023",confidence:"VERIFIED",url:"https://ajd.ijcp.in/Admin/CMS/PDF/5.%20GuestEditorial_AJD_JM2023.pdf"},
{id:"src-sk-3",type:"PUBLICATION",title:"Burden of Obesity in India: Need for Policy Changes",summary:"PubMed lists Kalra as lead author of a 2026 national policy paper on obesity and verifies his endocrinology affiliation at Bharti Hospital, Karnal.",publisher:"PubMed / Clinical Obesity",date:"Apr 2026",confidence:"VERIFIED",url:"https://pubmed.ncbi.nlm.nih.gov/41630400/"},
{id:"src-sk-4",type:"CONFERENCE",title:"The personal BMI threshold - What is the evidence?",summary:"The official ESICON 2026 scientific programme lists Kalra as the scheduled speaker in the special symposium on controversies in obesity.",publisher:"ESICON 2026 Scientific Programme",date:"Scheduled 22 Oct 2026",confidence:"VERIFIED",url:"https://www.esicon2026.com/scientific_programme.php"}]},
{id:"kol-rakesh-sahay",name:"Dr Rakesh Kumar Sahay",specialty:"Endocrinology",city:"Hyderabad",state:"Telangana",region:"South",affiliation:"Aster Prime Hospital",tier:"Regional KOL",matchConfidence:99,aliases:["Rakesh Sahay","Rakesh Kumar Sahay","Dr. Rakesh K. Sahay"],footprints:[
{id:"src-rs-1",type:"INSTITUTION",title:"Senior Consultant Endocrinologist",summary:"Aster's profile verifies Sahay's Hyderabad practice, prior Osmania leadership and professional society roles including obesity medicine.",publisher:"Aster Hospitals",date:"Current profile",confidence:"VERIFIED",url:"https://www.asterhospitals.in/doctors/aster-prime-hyderabad/dr-rakesh-kumar-sahay"},
{id:"src-rs-2",type:"PUBLICATION",title:"Academic endocrinology leadership",summary:"The institutional profile records a long research and teaching career spanning endocrinology, diabetes and metabolic disease.",publisher:"Aster Hospitals",date:"Current profile",confidence:"VERIFIED",url:"https://www.asterhospitals.in/doctors/aster-prime-hyderabad/dr-rakesh-kumar-sahay"}]},
{id:"kol-sujoy-ghosh",name:"Prof Sujoy Ghosh",specialty:"Endocrinology and metabolism",city:"Kolkata",state:"West Bengal",region:"East",affiliation:"IPGME&R; Manipal Hospitals Dhakuria",tier:"Scientific Leader",matchConfidence:99,aliases:["Sujoy Ghosh","Prof. Dr. Sujoy Ghosh"],footprints:[
{id:"src-sg-1",type:"INSTITUTION",title:"Professor, Endocrinology and Metabolism",summary:"IPGME&R's official faculty directory lists Ghosh as professor in the Department of Endocrinology and Metabolism in Kolkata.",publisher:"IPGME&R",date:"Current faculty list",confidence:"VERIFIED",url:"https://www.ipgmer.gov.in/endocrinology_metabolism"},
{id:"src-sg-2",type:"PUBLICATION",title:"Research and publication profile",summary:"The hospital profile records more than 300 publications, academic work at IPGME&R and broad metabolic and endocrine expertise.",publisher:"Manipal Hospitals",date:"Current profile",confidence:"VERIFIED",url:"https://www.manipalhospitals.com/dhakuria/doctors/dr-sujoy-ghosh-endocrinologist/"}]},
{id:"kol-prakhar-gupta",name:"Dr Prakhar Gupta",specialty:"Internal medicine and metabolic health",city:"Bhopal",state:"Madhya Pradesh",region:"Central",affiliation:"Sagar Multispeciality Hospital",tier:"Rising Voice",matchConfidence:97,aliases:["Prakhar Gupta","Dr. Prakhar Gupta"],footprints:[
{id:"src-pg-1",type:"INSTITUTION",title:"Consultant, Internal Medicine Services",summary:"The hospital profile verifies Gupta's Bhopal practice and lists endocrinology, diabetes, obesity and metabolic disorders among his clinical areas.",publisher:"Sagar Multispeciality Hospital",date:"Current profile",confidence:"VERIFIED",url:"https://www.smhbhopal.com/doctor-profile/66/dr-prakhar-gupta"},
{id:"src-pg-2",type:"PUBLICATION",title:"Published clinician and medical educator",summary:"The institutional profile records research publication and postgraduate teaching activity; individual publication-level verification remains in the research queue.",publisher:"Sagar Multispeciality Hospital",date:"Current profile",confidence:"REVIEW",url:"https://www.smhbhopal.com/doctor-profile/66/dr-prakhar-gupta"}]}
];
attachDiscoveredFootprints(researchProfiles);

// Reuse identity-linked profile evidence; post mentions are not clinician accounts.
for (const person of researchProfiles) {
  const profile = person.footprints.find(item => item.confidence === 'VERIFIED' && /^https:\/\/(?:www\.|in\.)?linkedin\.com\/in\//.test(item.url || ''));
  if (!profile) continue;
  socialAccounts.push({id:`social-${person.id}-linkedin`,hcpId:person.id,platform:'LinkedIn',handle:person.name,
    profileUrl:profile.url,identityStatus:'VERIFIED',collectionStatus:'CONNECTOR_REQUIRED',lastCheckedAt:null,
    source:'Existing identity-linked dossier; account not freshly checked',sourceRecordId:profile.id});
}
