// Obesity Voices India: specialist social listening corpus (THB listening wave, Mar 2025 to Sep 2026).
// Transcribed from the published Obesity Voices India report. Aggregates in the UI are computed from
// LISTENING_STATEMENTS so every chart reconciles to the coded ledger. Source URLs were not carried over
// from the report; each statement keeps its published source label and awaits link re-attachment.

export const LISTENING_META = Object.freeze({
  title: 'What India’s obesity specialists are saying about GLP-1 therapy',
  window: 'Mar 2025 – Sep 2026',
  updated: '23 Sep 2026',
  sourceTypesScanned: 29,
  products: ['Tirzepatide · Mounjaro / Yurpeak', 'Semaglutide · Wegovy / Ozempic', 'Generic semaglutide (35+ brands)', 'Bariatric & metabolic surgery'],
  patentExpiry: '2026-03-20',
  sourceLinksStatus: 'Every statement links to the page it was taken from. Links were located and checked against the quoted text on 28 Sep 2026.',
  corrections: 'Checking the sources corrected the listening report in three places. One cost quote belongs to Dr Yogesh Nain, not Dr Yogesh Kumar Chhabra. Two Business Today sentences on muscle loss and monthly cost are the article’s own text and were removed as specialist statements. Five quotes were restored to their published wording. The corpus is 65 statements from 36 voices.'
});

export const SENTIMENTS = Object.freeze(['Negative', 'Mixed / neutral', 'Positive']);
export const THEMES = Object.freeze([
  { name: 'Efficacy', detail: 'How well the drugs work' },
  { name: 'Safety & tolerability', detail: 'GI effects, titration, muscle, micronutrients, psychiatric signals' },
  { name: 'Cost', detail: 'Monthly price and the burden of continuous therapy' },
  { name: 'Availability & access', detail: 'Channels, supply, prescribing rights' },
  { name: 'Effect on patients', detail: 'QoL, adherence, regain after stopping' },
  { name: 'Impact & disease framing', detail: 'Chronic-disease framing, awareness, public health' },
  { name: 'Appropriate use & misuse', detail: 'Patient selection, cosmetic use, self-medication' },
  { name: 'Quality & counterfeits', detail: 'Counterfeits, generics, cold chain, recalls' }
]);
export const FRAMINGS = Object.freeze(['Caution', 'Education', 'Advocacy', 'Gatekeeping', 'Market commentary']);

export const LISTENING_STATEMENTS = Object.freeze([
  {"id":"L01","date":"2026-08-21","wave2":false,"who":"Dr K S Kular","role":"President, OSSI (bariatric surgery)","specialty":"Bariatric & metabolic surgery","text":"“Obesity is a chronic disease that requires timely recognition, scientific treatment and long-term care.”","paraphrased":false,"source":"Indian Pharma Post on OSSI–ESI consensus, Aug 2026","themes":["Impact & disease framing"],"sentiment":"Positive","framing":"Advocacy","channel":"Society publications & consensus"},
  {"id":"L02","date":"2026-08-21","wave2":false,"who":"Dr Kaushik Pandit","role":"President, Endocrine Society of India","specialty":"Endocrinology","text":"“India needs an approach to obesity that reflects the unique metabolic risks of our population.”","paraphrased":false,"source":"Indian Pharma Post on OSSI–ESI consensus, Aug 2026","themes":["Impact & disease framing"],"sentiment":"Positive","framing":"Advocacy","channel":"Society publications & consensus"},
  {"id":"L03","date":"2026-08-21","wave2":false,"who":"Dr Randeep Wadhawan","role":"Immediate Past President, OSSI (bariatric surgery)","specialty":"Bariatric & metabolic surgery","text":"“The important message from this consensus is that treatment should be individualised and timely.”","paraphrased":false,"source":"Indian Pharma Post on OSSI–ESI consensus, Aug 2026","themes":["Appropriate use & misuse","Impact & disease framing"],"sentiment":"Positive","framing":"Advocacy","channel":"Society publications & consensus"},
  {"id":"L04","date":"2026-08-21","wave2":false,"who":"Dr Aparna Govil Bhasker","role":"Bariatric & laparoscopic surgeon, Mumbai","specialty":"Bariatric & metabolic surgery","text":"“Obesity deserves the same scientific, compassionate and long-term approach as any other chronic disease.”","paraphrased":false,"source":"Indian Pharma Post on OSSI–ESI consensus, Aug 2026","themes":["Impact & disease framing"],"sentiment":"Positive","framing":"Advocacy","channel":"Society publications & consensus"},
  {"id":"L05","date":"2026-07-21","wave2":false,"who":"Asian Indian nutrition consensus","role":"Joshi, Misra, Mithal, Mohan and 9 others · Obesity Pillars","specialty":"Societies & multi-specialty panels","text":"“There is a need for structured nutritional support for individuals on GBTs, especially for Asian Indians, considering their diverse dietary intake and the high risk of sarcopenia.”","paraphrased":false,"source":"The South First on Asian Indian nutrition consensus, 21 Jul 2026","themes":["Safety & tolerability","Effect on patients"],"sentiment":"Mixed / neutral","framing":"Education","channel":"Society publications & consensus"},
  {"id":"L06","date":"2026-07-21","wave2":false,"who":"Asian Indian nutrition consensus","role":"Joshi, Misra, Mithal, Mohan and 9 others · Obesity Pillars","specialty":"Societies & multi-specialty panels","text":"“Individuals who discontinue the GBT may regain approximately two-thirds of their prior weight loss within one year due to inadequate lifestyle and nutritional support.”","paraphrased":false,"source":"The South First on Asian Indian nutrition consensus, 21 Jul 2026","themes":["Effect on patients"],"sentiment":"Negative","framing":"Caution","channel":"Society publications & consensus"},
  {"id":"L07","date":"2026-07-13","wave2":false,"who":"Dr Anoop Misra","role":"Chairman, Fortis C-DOC; Director, N-DOC, New Delhi","specialty":"Endocrinology","text":"“Modern weight-loss drugs such as semaglutide and tirzepatide represent a major advance, but weight loss alone does not guarantee meaningful improvements in quality of life and is often accompanied by muscle loss.”","paraphrased":false,"source":"X · @docanoopmisra, 13 Jul 2026","themes":["Effect on patients","Safety & tolerability"],"sentiment":"Mixed / neutral","framing":"Education","channel":"X (Twitter)"},
  {"id":"L08","date":"2026-07-10","wave2":true,"who":"Dr Rajiv Kovil","role":"Head of Diabetology, Zandra Healthcare, Mumbai","specialty":"Diabetology","text":"On the July generic recalls: “The industry owes clinicians and patients a transparent explanation regarding the underlying technical issue, its clinical significance and whether any patient safety concerns exist.”","paraphrased":false,"source":"Medical Dialogues on semaglutide recalls, 10 Jul 2026","themes":["Quality & counterfeits"],"sentiment":"Negative","framing":"Caution","channel":"Medical education & trade media"},
  {"id":"L09","date":"2026-06-29","wave2":false,"who":"Dr K P Singh","role":"Director, Endocrinology, Fortis Hospital, Mohali","specialty":"Endocrinology","text":"“Patients frequently struggle with persistent nausea, vomiting, a drastic loss of appetite, diarrhoea and severe constipation.”","paraphrased":false,"source":"Outlook Business, 29 Jun 2026","themes":["Safety & tolerability"],"sentiment":"Negative","framing":"Caution","channel":"Indian news & business media"},
  {"id":"L10","date":"2026-06-29","wave2":false,"who":"Dr Yogesh Nain","role":"General physician, Harley of London India","specialty":"General medicine","text":"“The high dropout rate highlights that obesity is a chronic disease requiring long-term management rather than a short-term treatment.”","paraphrased":false,"source":"Outlook Business, 29 Jun 2026","themes":["Effect on patients","Impact & disease framing"],"sentiment":"Mixed / neutral","framing":"Education","channel":"Indian news & business media"},
  {"id":"L11","date":"2026-06-29","wave2":false,"who":"Dr Ashish Gautam","role":"Principal Director, Robotic & Laparoscopic Surgery, Max, New Delhi","specialty":"Bariatric & metabolic surgery","text":"“Many patients expect these drugs alone to produce lasting weight loss, whereas obesity is a chronic disease that requires continuous lifestyle modification.”","paraphrased":false,"source":"Outlook Business, 29 Jun 2026","themes":["Effect on patients"],"sentiment":"Mixed / neutral","framing":"Caution","channel":"Indian news & business media"},
  {"id":"L12","date":"2026-06-29","wave2":false,"who":"Dr Yogesh Nain","role":"General physician, Harley of London India","specialty":"General medicine","text":"“Most GLP-1 therapies require continuous treatment, and the monthly cost is beyond the reach of many Indian patients.”","paraphrased":false,"source":"Outlook Business, 29 Jun 2026","themes":["Cost"],"sentiment":"Negative","framing":"Caution","channel":"Indian news & business media","correction":"Attributed to Dr Yogesh Kumar Chhabra in the listening report; the source attributes it to Dr Yogesh Nain."},
  {"id":"L13","date":"2026-05-10","wave2":false,"who":"Dr Preethi Mrinalini","role":"Laparoscopic & bariatric surgeon, Chennai","specialty":"Bariatric & metabolic surgery","text":"“One good thing that’s actually happened is obesity awareness.”","paraphrased":false,"source":"ABC News, 10 May 2026","themes":["Impact & disease framing"],"sentiment":"Positive","framing":"Advocacy","channel":"International media & wires"},
  {"id":"L14","date":"2026-05-10","wave2":false,"who":"Dr Preethi Mrinalini","role":"Laparoscopic & bariatric surgeon, Chennai","specialty":"Bariatric & metabolic surgery","text":"On people without an indication: “I know for a fact they are able to get themselves on it somehow, which is not OK.”","paraphrased":false,"source":"ABC News, 10 May 2026","themes":["Appropriate use & misuse","Availability & access"],"sentiment":"Negative","framing":"Caution","channel":"International media & wires"},
  {"id":"L15","date":"2026-05-10","wave2":false,"who":"Amita Gadre","role":"Nutritionist, Pune","specialty":"Nutrition & dietetics","text":"On dose titration: “If this process is hurried or not done properly, patients are at a much higher risk of experiencing severe gastrointestinal side effects.”","paraphrased":false,"source":"ABC News, 10 May 2026","themes":["Safety & tolerability"],"sentiment":"Negative","framing":"Caution","channel":"International media & wires"},
  {"id":"L16","date":"2026-05-10","wave2":false,"who":"Amita Gadre","role":"Nutritionist, Pune","specialty":"Nutrition & dietetics","text":"“The drugs are now available through multiple channels, raising the risk of people obtaining them without proper medical supervision.”","paraphrased":false,"source":"ABC News, 10 May 2026","themes":["Availability & access","Appropriate use & misuse"],"sentiment":"Negative","framing":"Caution","channel":"International media & wires"},
  {"id":"L17","date":"2026-05-06","wave2":true,"who":"Dr Anoop Misra","role":"Chairman, Fortis C-DOC; Director, N-DOC, New Delhi","specialty":"Endocrinology","text":"“These drugs are increasingly being used inappropriately, often without proper medical evaluation.”","paraphrased":false,"source":"Business Today, 6 May 2026","themes":["Appropriate use & misuse"],"sentiment":"Negative","framing":"Caution","channel":"Indian news & business media"},
  {"id":"L18","date":"2026-05-06","wave2":true,"who":"Dr Anoop Misra","role":"Chairman, Fortis C-DOC; Director, N-DOC, New Delhi","specialty":"Endocrinology","text":"“These medications work best when combined with structured lifestyle changes, not as a replacement for them.”","paraphrased":false,"source":"Business Today, 6 May 2026","themes":["Effect on patients"],"sentiment":"Mixed / neutral","framing":"Education","channel":"Indian news & business media"},
  {"id":"L19","date":"2026-05-05","wave2":true,"who":"Dr Sanjay Kalra","role":"Endocrinologist, Karnal · Chair, OBESITAS 2026 organising committee","specialty":"Endocrinology","text":"“We are at a tipping point. Obesity is now driving a large part of India’s diabetes, heart disease, and metabolic burden, yet it continues to be under-treated.”","paraphrased":false,"source":"Indian Pharma Post on OBESITAS 2026, 5 May 2026","themes":["Impact & disease framing"],"sentiment":"Positive","framing":"Advocacy","channel":"Conference / CME"},
  {"id":"L20","date":"2026-05-05","wave2":true,"who":"Dr Saptarshi Bhattacharya","role":"Endocrinologist, New Delhi · OBESITAS 2026 organising committee","specialty":"Endocrinology","text":"“Obesity management is becoming more precise, more personalised, and more integrated, with nutrition, behaviour, and newer therapies working together rather than in isolation.”","paraphrased":false,"source":"Indian Pharma Post on OBESITAS 2026, 5 May 2026","themes":["Efficacy","Impact & disease framing"],"sentiment":"Positive","framing":"Advocacy","channel":"Conference / CME"},
  {"id":"L21","date":"2026-05-05","wave2":true,"who":"Dr Shweta Wazir","role":"Obstetrics & gynaecology, Motherhood Hospitals","specialty":"Obstetrics & gynaecology","text":"On PCOS: “There is a noticeable shift from symptom-based treatment to a metabolic-focused approach, with GLP-1 therapies showing improvements in menstrual regularity, skin concerns, and fertility outcomes.”","paraphrased":false,"source":"Motherhood Hospitals media coverage, May 2026","themes":["Efficacy"],"sentiment":"Positive","framing":"Advocacy","channel":"Hospital & clinic blogs"},
  {"id":"L22","date":"2026-04-30","wave2":false,"who":"Endocrinologist (unnamed)","role":"Mumbai","specialty":"Endocrinology","text":"On counterfeit Mounjaro: “The risk is particularly high in chronic conditions like diabetes, where continuity and accuracy of treatment are crucial.”","paraphrased":false,"source":"The Week, 30 Apr 2026","themes":["Quality & counterfeits","Safety & tolerability"],"sentiment":"Negative","framing":"Caution","channel":"Indian news & business media"},
  {"id":"L23","date":"2026-04-25","wave2":true,"who":"Dr Ambrish Mithal","role":"Chairman, Endocrinology & Diabetes, Max Healthcare, New Delhi","specialty":"Endocrinology","text":"Shares an Indian Express report that generics “flooding the market” are “reshaping both demand and prescribing patterns.”","paraphrased":true,"source":"X · @DrAmbrishMithal, 25 Apr 2026","themes":["Availability & access","Cost"],"sentiment":"Mixed / neutral","framing":"Market commentary","channel":"X (Twitter)"},
  {"id":"L24","date":"2026-04-06","wave2":true,"who":"Max Healthcare endocrinology team","role":"Jarso, Mahendru, Dutta, Sharma, Megerso, Mithal · Indian J Endocrinol Metab (n=150)","specialty":"Endocrinology","text":"“In this real-world Indian cohort, GLP-1/GIP receptor agonist therapy was effective in achieving clinically meaningful weight loss in adults with obesity.” (tirzepatide 8.60% vs semaglutide 5.62%)","paraphrased":false,"source":"Indian J Endocrinol Metab (Max Healthcare real-world study), 6 Apr 2026","themes":["Efficacy"],"sentiment":"Positive","framing":"Education","channel":"Peer-reviewed research"},
  {"id":"L25","date":"2026-04-04","wave2":false,"who":"Dr Rajat Goel","role":"Bariatric surgeon, Hindivine Healthcare, New Delhi","specialty":"Bariatric & metabolic surgery","text":"“Over the last few months, over 20 per cent of the queries we’ve received for obesity injections are from to-be brides.”","paraphrased":false,"source":"Malay Mail / Reuters, 4 Apr 2026","themes":["Appropriate use & misuse"],"sentiment":"Mixed / neutral","framing":"Market commentary","channel":"International media & wires"},
  {"id":"L26","date":"2026-04-04","wave2":false,"who":"Dr Swati Pradhan","role":"Founder, Live Light obesity & metabolic clinic","specialty":"Obesity clinic","text":"“We understand the curiosity, but this cannot be a quick fix.”","paraphrased":false,"source":"Malay Mail / Reuters, 4 Apr 2026","themes":["Appropriate use & misuse"],"sentiment":"Negative","framing":"Caution","channel":"International media & wires"},
  {"id":"L27","date":"2026-04-01","wave2":true,"who":"Dr. Mohan's Diabetes Specialities Centre","role":"Diabetology centre, Chennai (institutional blog)","specialty":"Diabetology","text":"“When used under proper medical supervision, these treatments can be safe and effective.”","paraphrased":false,"source":"Dr. Mohan's Diabetes Specialities Centre blog, 1 Apr 2026","themes":["Safety & tolerability"],"sentiment":"Positive","framing":"Education","channel":"Hospital & clinic blogs"},
  {"id":"L28","date":"2026-04-01","wave2":true,"who":"Dr. Mohan's Diabetes Specialities Centre","role":"Diabetology centre, Chennai (institutional blog)","specialty":"Diabetology","text":"“Using weight loss injections without proper supervision can lead to serious consequences.”","paraphrased":false,"source":"Dr. Mohan's Diabetes Specialities Centre blog, 1 Apr 2026","themes":["Appropriate use & misuse","Safety & tolerability"],"sentiment":"Negative","framing":"Caution","channel":"Hospital & clinic blogs"},
  {"id":"L29","date":"2026-03-25","wave2":true,"who":"Dr Anil Kumar J. Nayak","role":"National President, Indian Medical Association","specialty":"Societies & multi-specialty panels","text":"“We will give a memorandum to the govt for restricting prescriptions of GLP-1 drugs to certified endocrinologists/Diabetologists or MD general medicine to curb misuse.”","paraphrased":false,"source":"ANI, 25 Mar 2026","themes":["Appropriate use & misuse","Availability & access"],"sentiment":"Negative","framing":"Gatekeeping","channel":"Indian news & business media"},
  {"id":"L30","date":"2026-03-24","wave2":true,"who":"Dr Rajiv Kovil","role":"Head of Diabetology, Zandra Healthcare, Mumbai","specialty":"Diabetology","text":"“Semaglutide is an 11-year-old molecule with nearly 50 clinical trials behind it. It has very robust data, largely built by Novo Nordisk.”","paraphrased":false,"source":"The Week, 24 Mar 2026","themes":["Efficacy"],"sentiment":"Positive","framing":"Education","channel":"Indian news & business media"},
  {"id":"L31","date":"2026-03-24","wave2":true,"who":"Dr Rajiv Kovil","role":"Head of Diabetology, Zandra Healthcare, Mumbai","specialty":"Diabetology","text":"“There is about a 28% reduction in heart disease risk and nearly a 24% reduction in kidney-related events.”","paraphrased":false,"source":"The Week, 24 Mar 2026","themes":["Efficacy","Impact & disease framing"],"sentiment":"Positive","framing":"Advocacy","channel":"Indian news & business media"},
  {"id":"L32","date":"2026-03-24","wave2":true,"who":"Dr Rajiv Kovil","role":"Head of Diabetology, Zandra Healthcare, Mumbai","specialty":"Diabetology","text":"“Semaglutide is a peptide and a difficult drug to manufacture. It also requires strict cold chain maintenance… Any break in this chain can lead to batch-to-batch variation.”","paraphrased":false,"source":"The Week, 24 Mar 2026","themes":["Quality & counterfeits"],"sentiment":"Negative","framing":"Caution","channel":"Indian news & business media"},
  {"id":"L33","date":"2026-03-24","wave2":true,"who":"Dr Rajiv Kovil","role":"Head of Diabetology, Zandra Healthcare, Mumbai","specialty":"Diabetology","text":"“When prices come down, more people, especially the middle class, will be able to afford it. But this is not a magic bullet for weight loss.”","paraphrased":false,"source":"The Week, 24 Mar 2026","themes":["Cost","Effect on patients"],"sentiment":"Mixed / neutral","framing":"Education","channel":"Indian news & business media"},
  {"id":"L34","date":"2026-03-23","wave2":true,"who":"Dr Nikhil Tandon","role":"Professor & Head, Endocrinology & Metabolism, AIIMS, New Delhi","specialty":"Endocrinology","text":"“One should not consume it (generic semaglutide) recklessly as these are serious medicines for a serious problem.”","paraphrased":false,"source":"ANI via India's News, 23 Mar 2026","themes":["Appropriate use & misuse","Quality & counterfeits"],"sentiment":"Negative","framing":"Caution","channel":"Indian news & business media"},
  {"id":"L35","date":"2026-03-23","wave2":true,"who":"Dr Nikhil Tandon","role":"Professor & Head, Endocrinology & Metabolism, AIIMS, New Delhi","specialty":"Endocrinology","text":"“The medicines which are used in weight control are always given with a foundation of diet control and physical activity.”","paraphrased":false,"source":"ANI via India's News, 23 Mar 2026","themes":["Effect on patients"],"sentiment":"Mixed / neutral","framing":"Education","channel":"Indian news & business media"},
  {"id":"L36","date":"2026-03-23","wave2":false,"who":"Dr Rajiv Kovil","role":"Head of Diabetology, Zandra Healthcare, Mumbai","specialty":"Diabetology","text":"Advises a “wait-and-watch” approach before switching stable patients to new generic brands, until cold-chain and distribution reliability are proven.","paraphrased":true,"source":"OC Academy, 23 Mar 2026","themes":["Quality & counterfeits","Availability & access"],"sentiment":"Mixed / neutral","framing":"Caution","channel":"Medical education & trade media"},
  {"id":"L37","date":"2026-03-16","wave2":false,"who":"National cardiology expert panel","role":"Consensus in J Assoc Physicians India","specialty":"Cardiology","text":"“Semaglutide represents a practice-changing therapy that addresses core pathophysiological drivers of atherosclerotic cardiovascular disease.”","paraphrased":false,"source":"The South First on JAPI cardiology consensus, 16 Mar 2026","themes":["Efficacy","Impact & disease framing"],"sentiment":"Positive","framing":"Advocacy","channel":"Society publications & consensus"},
  {"id":"L38","date":"2026-03-16","wave2":false,"who":"National cardiology expert panel","role":"Consensus in J Assoc Physicians India","specialty":"Cardiology","text":"“Obesity is increasingly recognized as a chronic, relapsing, and progressive disease that acts as a major upstream driver of cardiovascular, kidney, and metabolic disorders.”","paraphrased":false,"source":"The South First on JAPI cardiology consensus, 16 Mar 2026","themes":["Impact & disease framing"],"sentiment":"Positive","framing":"Advocacy","channel":"Society publications & consensus"},
  {"id":"L39","date":"2026-03-13","wave2":true,"who":"Dr Vitish Singla","role":"GI, Minimal Access & Bariatric Surgery, Fortis, Mohali","specialty":"Bariatric & metabolic surgery","text":"Positions injections for “BMI 30-40 with metabolic comorbidities” or as a bridge to surgery, and warns “15-20% of lost weight returns upon medication discontinuation.”","paraphrased":true,"source":"Fortis Healthcare blog, 13 Mar 2026","themes":["Effect on patients","Appropriate use & misuse"],"sentiment":"Mixed / neutral","framing":"Education","channel":"Hospital & clinic blogs"},
  {"id":"L40","date":"2026-03-04","wave2":true,"who":"Dr Amit Bhargava & Dr Varsha Narayanan","role":"Family physician (H.E.A.R.T) & Chief Editor, The Indian Practitioner, Mumbai","specialty":"General medicine","text":"“Ready availability of these drugs without prescriptions or medical consultations in pharmacies and online platforms needs curbing.”","paraphrased":false,"source":"The Indian Practitioner, Mar 2026","themes":["Availability & access","Appropriate use & misuse"],"sentiment":"Negative","framing":"Caution","channel":"Medical education & trade media"},
  {"id":"L41","date":"2026-03-04","wave2":true,"who":"Dr Amit Bhargava & Dr Varsha Narayanan","role":"Family physician (H.E.A.R.T) & Chief Editor, The Indian Practitioner, Mumbai","specialty":"General medicine","text":"“Launch of OTC oral GLP1-RA as health supplement without published clinical data or adequate safety evaluation is highly concerning.”","paraphrased":false,"source":"The Indian Practitioner, Mar 2026","themes":["Quality & counterfeits","Safety & tolerability"],"sentiment":"Negative","framing":"Caution","channel":"Medical education & trade media"},
  {"id":"L42","date":"2026-03-04","wave2":true,"who":"Dr Amit Bhargava & Dr Varsha Narayanan","role":"Family physician (H.E.A.R.T) & Chief Editor, The Indian Practitioner, Mumbai","specialty":"General medicine","text":"“Individualised prescribing decisions after thorough evaluation of patient fitment and risks, along with regular and meticulous monitoring for adverse effects is pertinent.”","paraphrased":false,"source":"The Indian Practitioner, Mar 2026","themes":["Safety & tolerability","Appropriate use & misuse"],"sentiment":"Mixed / neutral","framing":"Gatekeeping","channel":"Medical education & trade media"},
  {"id":"L43","date":"2026-02-01","wave2":true,"who":"Dr Ameya Joshi","role":"Consultant Endocrinologist & Diabetologist · RSSDI IDEJ interview","specialty":"Endocrinology","text":"“Weight loss has emerged as a legitimate therapeutic goal, not merely a lifestyle aspiration.”","paraphrased":false,"source":"RSSDI IDEJ newsletter, Issue 131, Feb 2026","themes":["Impact & disease framing"],"sentiment":"Positive","framing":"Advocacy","channel":"Society publications & consensus"},
  {"id":"L44","date":"2026-02-01","wave2":true,"who":"Dr Ambuj Yadav","role":"Associate Professor of Medicine, KGMU, Lucknow · RSSDI IDEJ","specialty":"General medicine","text":"“Their glucose-dependent mechanism, simplified dosing strategies, and overall favorable safety profile makes them effective and durable therapeutic options.”","paraphrased":false,"source":"RSSDI IDEJ newsletter, Issue 131, Feb 2026","themes":["Safety & tolerability"],"sentiment":"Positive","framing":"Education","channel":"Society publications & consensus"},
  {"id":"L45","date":"2025-12-23","wave2":false,"who":"Dr Anoop Misra","role":"Chairman, Fortis C-DOC; Director, N-DOC, New Delhi","specialty":"Endocrinology","text":"“Mounjaro clearly has first-strike advantage and continues to have strong demand, but price-sensitive patients are reassessing alternatives.”","paraphrased":false,"source":"Reuters (syndicated), 23 Dec 2025","themes":["Cost","Availability & access"],"sentiment":"Mixed / neutral","framing":"Market commentary","channel":"International media & wires"},
  {"id":"L46","date":"2025-12-20","wave2":false,"who":"Dr Arjita K Kumar","role":"Consultant Physician & Diabetologist, Polaris Hospital, Gurugram","specialty":"Diabetology","text":"“I receive many queries from people who are not obese but merely overweight. These people do not medically qualify for the treatment, and I have to refuse them.”","paraphrased":false,"source":"Outlook Business, 20 Dec 2025","themes":["Appropriate use & misuse"],"sentiment":"Mixed / neutral","framing":"Gatekeeping","channel":"Indian news & business media"},
  {"id":"L47","date":"2025-12-20","wave2":false,"who":"Dr Aparna Govil Bhasker","role":"Bariatric & laparoscopic surgeon, Mumbai","specialty":"Bariatric & metabolic surgery","text":"“It is encouraging that they bring their questions to doctors, because that allows us to guide them accurately and responsibly.”","paraphrased":false,"source":"Outlook Business, 20 Dec 2025","themes":["Impact & disease framing"],"sentiment":"Positive","framing":"Advocacy","channel":"Indian news & business media"},
  {"id":"L48","date":"2025-12-18","wave2":false,"who":"Dr Muffazal Lakdawala","role":"Bariatric surgeon, Mumbai","specialty":"Bariatric & metabolic surgery","text":"“These are lifesaving drugs, but the worrying trend is that they are being misused for weight loss by self-medication and by non-qualified quacks.”","paraphrased":false,"source":"Esquire India, 18 Dec 2025","themes":["Efficacy","Appropriate use & misuse"],"sentiment":"Mixed / neutral","framing":"Caution","channel":"Lifestyle interview"},
  {"id":"L49","date":"2025-12-18","wave2":false,"who":"Dr Muffazal Lakdawala","role":"Bariatric surgeon, Mumbai","specialty":"Bariatric & metabolic surgery","text":"“There is nothing like mini dosing of Ozempic or Mounjaro… if you have got only 5–8 kgs to lose, follow a diet, take the sugar off, and exercise regularly.”","paraphrased":false,"source":"Esquire India, 18 Dec 2025","themes":["Appropriate use & misuse"],"sentiment":"Negative","framing":"Gatekeeping","channel":"Lifestyle interview"},
  {"id":"L50","date":"2025-11-04","wave2":true,"who":"RSSDI 2025 obesity track","role":"53rd RSSDI Annual Conference, Kochi · faculty incl. S. Joshi, K. Seshadri, M. Bhandari (conference preview)","specialty":"Societies & multi-specialty panels","text":"“Dual GIP and GLP-1 receptor agonism represents an advancement in the medical management of obesity.”","paraphrased":false,"source":"Medical Dialogues on RSSDI 2025 obesity track","themes":["Efficacy"],"sentiment":"Positive","framing":"Education","channel":"Conference / CME","correction":"Conference-preview wording in Medical Dialogues, not attributed to a named speaker."},
  {"id":"L51","date":"2025-11-04","wave2":true,"who":"RSSDI 2025 obesity track","role":"53rd RSSDI Annual Conference, Kochi · faculty incl. S. Joshi, K. Seshadri, M. Bhandari (conference preview)","specialty":"Societies & multi-specialty panels","text":"“With 1 out of 7 Indians being overweight, staying abreast of the latest therapeutic options has become crucial.”","paraphrased":false,"source":"Medical Dialogues on RSSDI 2025 obesity track","themes":["Impact & disease framing"],"sentiment":"Positive","framing":"Advocacy","channel":"Conference / CME","correction":"Conference-preview wording in Medical Dialogues, not attributed to a named speaker."},
  {"id":"L52","date":"2025-08-26","wave2":true,"who":"ESI obesity guideline panel","role":"Madhu, Kapoor, Das, Raizada, Kalra · ESI Clinical Practice Guidelines 2025","specialty":"Endocrinology","text":"“Tirzepatide should be considered where a weight loss target of 15%–20% is targeted.”","paraphrased":false,"source":"ESI Clinical Practice Guidelines for Obesity – 2025 update (IJEM, PMC)","themes":["Efficacy"],"sentiment":"Positive","framing":"Education","channel":"Society publications & consensus"},
  {"id":"L53","date":"2025-08-26","wave2":true,"who":"ESI obesity guideline panel","role":"Madhu, Kapoor, Das, Raizada, Kalra · ESI Clinical Practice Guidelines 2025","specialty":"Endocrinology","text":"“Proper counselling for anti-obesity medications must precede their usage. The counselling should continue during the treatment.”","paraphrased":false,"source":"ESI Clinical Practice Guidelines for Obesity – 2025 update (IJEM, PMC)","themes":["Appropriate use & misuse"],"sentiment":"Mixed / neutral","framing":"Gatekeeping","channel":"Society publications & consensus"},
  {"id":"L54","date":"2025-08-18","wave2":true,"who":"Dr Ambrish Mithal","role":"Chairman, Endocrinology & Diabetes, Max Healthcare, New Delhi","specialty":"Endocrinology","text":"Sharing his conversation with Barkha Dutt on “The Weight Loss Revolution”: “Always use under medical supervision • A great scientific advance—not a substitute for diet and exercise • Ask your doctor”","paraphrased":false,"source":"X · @DrAmbrishMithal, 18 Aug 2025","themes":["Efficacy","Appropriate use & misuse"],"sentiment":"Mixed / neutral","framing":"Education","channel":"X (Twitter)"},
  {"id":"L55","date":"2025-06-29","wave2":false,"who":"Dr Ambrish Mithal","role":"Chairman, Endocrinology & Diabetes, Max Healthcare, New Delhi","specialty":"Endocrinology","text":"“A 20 per cent weight reduction is a game-changer for the obese.”","paraphrased":false,"source":"The Tribune, 29 Jun 2025","themes":["Efficacy"],"sentiment":"Positive","framing":"Advocacy","channel":"Indian news & business media"},
  {"id":"L56","date":"2025-06-29","wave2":false,"who":"Dr Ambrish Mithal","role":"Chairman, Endocrinology & Diabetes, Max Healthcare, New Delhi","specialty":"Endocrinology","text":"“We have been using these GLP-1 drugs routinely for our diabetes patients.”","paraphrased":false,"source":"The Tribune, 29 Jun 2025","themes":["Safety & tolerability"],"sentiment":"Positive","framing":"Education","channel":"Indian news & business media"},
  {"id":"L57","date":"2025-06-29","wave2":false,"who":"Dr Anoop Misra","role":"Chairman, Fortis C-DOC; Director, N-DOC, New Delhi","specialty":"Endocrinology","text":"“Their basic mechanism is not new as similar agents from earlier generations have been in use for over two decades.”","paraphrased":false,"source":"The Tribune, 29 Jun 2025","themes":["Safety & tolerability","Efficacy"],"sentiment":"Mixed / neutral","framing":"Education","channel":"Indian news & business media"},
  {"id":"L58","date":"2025-06-29","wave2":false,"who":"Dr Sachin Mittal","role":"Consultant Endocrinology, Fortis, Mohali","specialty":"Endocrinology","text":"“Some of these medications have the potential to cause weight loss up to 22 per cent of the body weight.”","paraphrased":false,"source":"The Tribune, 29 Jun 2025","themes":["Efficacy"],"sentiment":"Positive","framing":"Advocacy","channel":"Indian news & business media"},
  {"id":"L59","date":"2025-06-29","wave2":false,"who":"Dr Sachin Mittal","role":"Consultant Endocrinology, Fortis, Mohali","specialty":"Endocrinology","text":"“These drugs should be taken only on the advice of a doctor.”","paraphrased":false,"source":"The Tribune, 29 Jun 2025","themes":["Appropriate use & misuse"],"sentiment":"Mixed / neutral","framing":"Gatekeeping","channel":"Indian news & business media"},
  {"id":"L60","date":"2025-06-25","wave2":false,"who":"Dr Sudhir Kumar","role":"Neurologist, Hyderabad","specialty":"Neurology","text":"“Semaglutide (Wegovy) & Tirzepatide (Mounjaro): What You Should Know…” (thread on who needs these drugs)","paraphrased":false,"source":"X · @hyderabaddoctor, 25 Jun 2025","themes":["Efficacy","Appropriate use & misuse"],"sentiment":"Mixed / neutral","framing":"Education","channel":"X (Twitter)"},
  {"id":"L61","date":"2025-06-01","wave2":true,"who":"Lt Gen (Dr) Narendra Kotwal","role":"President, Endocrine Society of India · Mid-ESICON 2025, Chandigarh","specialty":"Endocrinology","text":"“Metabolic health is intricately tied to our environment. We must eat less, walk more, smile more, and live in the present.”","paraphrased":false,"source":"The Tribune on Mid-ESICON 2025, 1 Jun 2025","themes":["Impact & disease framing"],"sentiment":"Mixed / neutral","framing":"Education","channel":"Conference / CME"},
  {"id":"L62","date":"2025-03-25","wave2":false,"who":"Dr Sudhir Kumar","role":"Neurologist, Hyderabad","specialty":"Neurology","text":"“It is always better to prevent reaching a stage where such medication becomes necessary.”","paraphrased":false,"source":"The South First, 25 Mar 2025","themes":["Impact & disease framing","Appropriate use & misuse"],"sentiment":"Mixed / neutral","framing":"Caution","channel":"Indian news & business media"},
  {"id":"L63","date":"2025-03-25","wave2":false,"who":"Dr Sudhir Kumar","role":"Neurologist, Hyderabad","specialty":"Neurology","text":"“Don’t fall into this trap. Take charge of your health and prevent becoming a patient.”","paraphrased":false,"source":"The South First, 25 Mar 2025","themes":["Appropriate use & misuse"],"sentiment":"Negative","framing":"Caution","channel":"Indian news & business media"},
  {"id":"L64","date":"2025-03-25","wave2":false,"who":"Dr Nandita Iyer","role":"Nutritionist, Bengaluru","specialty":"Nutrition & dietetics","text":"“You still need proper nutrition, physical activity, and lifestyle changes—no injection can outrun a bad lifestyle.”","paraphrased":false,"source":"The South First, 25 Mar 2025","themes":["Effect on patients"],"sentiment":"Mixed / neutral","framing":"Education","channel":"Indian news & business media"},
  {"id":"L65","date":"2025-03-05","wave2":false,"who":"Dr Sudhir Kumar","role":"Neurologist, Hyderabad","specialty":"Neurology","text":"“No to fat shaming, yes to inane weight loss fads: Hypocrisy, habit or circumstance?” (shares a News9 article citing his post)","paraphrased":false,"source":"X · @hyderabaddoctor, 5 Mar 2025","themes":["Appropriate use & misuse"],"sentiment":"Negative","framing":"Caution","channel":"X (Twitter)"}
]);

export const LISTENING_SUMMARY = Object.freeze({
  headline: 'Specialists back the science but push back on how the drugs are used',
  lede: 'Across 18 months of public commentary, India’s obesity and diabetes specialists agree that GLP-1 and GIP/GLP-1 therapies work. They are divided on who should get them, who should prescribe them, how long patients should stay on them, and whether cheaper generics can be trusted.',
  story: 'We coded **65 public statements** from **36 specialists, institutions and panels**. They came from news media, X, society guidelines, conferences, journals, hospital blogs and trade media. Net sentiment is **+6**, a balanced overall picture that hides a sharp split. **Efficacy** gets no negative statements, and **disease framing** is strongly positive. **Appropriate use and misuse** is the most discussed theme (22 statements, 11 negative). Tone moved from explaining the drugs in 2025 (net +19) to warnings about generics, recalls, muscle loss and prescribing rights in 2026 (net 0).',
  leadership: [
    { lead: 'Efficacy is no longer the argument.', body: 'Specialists quote 15–22% weight loss, CV and renal benefit, and Indian real-world data (Max Healthcare: tirzepatide 8.6% vs semaglutide 5.6%) as settled. Differentiation must come from what happens after weight loss: lean mass, maintenance and outcomes.' },
    { lead: 'Misuse and quality now drive sentiment.', body: 'Most negative statements are about self-medication, “Mounjaro brides”, online and clinic supply, counterfeits and the July 2026 generic recalls. Brands seen as the safe, supervised choice will earn specialist trust.' },
    { lead: 'Who may prescribe is contested.', body: 'The IMA wants prescribing limited to endocrinologists, diabetologists and MD physicians. Societies (ESI, OSSI, RSSDI, cardiology panels) are writing the protocols. Engagement plans should follow this shift in authority.' }
  ],
  insights: [
    { tag: 'Efficacy', theme: 'Efficacy', title: 'Efficacy is settled, and specialists quote it as a number', body: 'No specialist disputes efficacy. They cite 15–22% weight loss, 28% CV and 24% renal risk reduction, and Indian real-world data showing tirzepatide ahead of semaglutide.', quote: '“A 20 per cent weight reduction is a game-changer for the obese.”', by: 'Dr Ambrish Mithal · 29 Jun 2025' },
    { tag: 'Appropriate use', theme: 'Appropriate use & misuse', title: 'Misuse is the loudest negative theme', body: 'Brides, mini-dosing, quacks, online and clinic supply, and generics taken “recklessly”. AIIMS, IMA, bariatric surgeons and nutritionists all warn against unsupervised use.', quote: '“One should not consume it (generic semaglutide) recklessly as these are serious medicines for a serious problem.”', by: 'Dr Nikhil Tandon · 23 Mar 2026' },
    { tag: 'Effect over time', theme: 'Effect on patients', title: '2026 asks: what happens after the weight comes off?', body: 'Muscle loss (25–35% of weight lost), micronutrient gaps, dropout, and regain of about two-thirds of lost weight within a year of stopping.', quote: '“Individuals who discontinue the GBT may regain approximately two-thirds of their prior weight loss within one year due to inadequate lifestyle and nutritional support.”', by: 'Asian Indian nutrition consensus · 21 Jul 2026' },
    { tag: 'Quality & generics', theme: 'Quality & counterfeits', title: 'Generic quality is now a clinical concern', body: 'Cold chain, batch variation, counterfeit Mounjaro, OTC “oral GLP-1 supplements” and the July 2026 recalls led diabetologists to ask manufacturers for transparency.', quote: 'On the July generic recalls: “The industry owes clinicians and patients a transparent explanation regarding the underlying technical issue.”', by: 'Dr Rajiv Kovil · 10 Jul 2026' },
    { tag: 'Prescribing authority', theme: 'Availability & access', title: 'Who may prescribe is now contested', body: 'The IMA seeks limits to endocrinologists, diabetologists and MD physicians. ESI requires counselling before and during therapy. Societies are writing the protocols.', quote: '“We will give a memorandum to the govt for restricting prescriptions of GLP-1 drugs to certified endocrinologists/Diabetologists or MD general medicine to curb misuse.”', by: 'Dr Anil Kumar J. Nayak · 25 Mar 2026' },
    { tag: 'Chronic disease', theme: 'Impact & disease framing', title: 'Obesity is being reframed as an under-treated chronic disease', body: 'Cardiologists, OSSI–ESI, OBESITAS and RSSDI frame obesity as chronic, relapsing and under-treated. This is the most positive theme in the corpus.', quote: '“We are at a tipping point. Obesity now drives large parts of India’s diabetes, heart disease, and metabolic burden, yet remains under-treated.”', by: 'Dr Sanjay Kalra · 05 May 2026' },
    { tag: 'Who is critical', specialtyView: true, title: 'Core specialists lean positive, adjacent voices lean negative', body: 'Endocrinology and bariatric surgery are net positive. Nutrition, neurology, general practice and wellness clinics are net negative, and they reach consumers directly.', quote: '“Most GLP-1 therapies require continuous treatment, and the monthly cost is beyond the reach of many Indian patients.”', by: 'Dr Yogesh Nain · 29 Jun 2026' },
    { tag: 'Blind spots', sourceView: true, title: 'Closed and regional platforms are the next frontier', body: 'WhatsApp, Telegram, ShareChat, Moj, Josh and Instagram could not be collected, and Instagram is dominated by clinic promotion. Regional signals (Hindi, Telugu) are growing.' }
  ]
});

export const THEME_DETAIL = Object.freeze({
  'Efficacy': { points: [['Magnitude', '15–22% weight loss is cited by Mithal, Mittal and Kovil. ESI positions tirzepatide for 15–20% targets.'], ['Indian real-world data', 'Max Healthcare (n=150): tirzepatide 8.6% vs semaglutide 5.6%. Non-diabetics lose more (11.2% vs 5.5%).'], ['Beyond weight', '28% CV and 24% renal event reduction (Kovil). Cardiology panel calls semaglutide practice-changing.'], ['New indications', 'PCOS gains in menstrual regularity, skin and fertility (Motherhood Hospitals, off-label).']], soWhat: 'Efficacy is the price of entry. To differentiate, move the story to outcomes beyond the scale (CV, renal, QoL) and to Indian real-world data.' },
  'Safety & tolerability': { points: [['GI tolerability', 'Nausea, vomiting and constipation are common. Hurried titration raises GI risk (KP Singh, Gadre).'], ['Muscle & bone', '25–35% of weight lost can be lean mass, especially in older adults (consensus, Misra).'], ['Micronutrients', 'Vitamin D, B12 and iron deficits rise on therapy. Consensus asks for monitoring.'], ['Emerging signals', 'Psychiatric (TGA warning covered in Hindi media) and hair-loss studies. Indian J Psychiatry calls for metabo-psychiatry care.']], soWhat: 'Tolerability talk is about GI burden and titration discipline, and now muscle, micronutrient and mental-health signals too. Titration support and nutrition protocols are the answer.' },
  'Cost': { points: [['Innovator price', '₹10,000–25,000 a month limits access (Business Today). Mounjaro ₹13,125–25,781.'], ['Generic price', '₹1,200–8,000 a month since Mar 2026. The middle class can now afford it (Kovil).'], ['Continuous therapy', 'Lifelong treatment, not the first month, is the real barrier (Nain).'], ['No reimbursement', 'Cardiology panel asks for insurance coverage. The drugs are not on the NLEM.']], soWhat: 'Cost is a barrier to staying on therapy, not to starting it. Plan pricing, packs and support for year two, not month one.' },
  'Availability & access': { points: [['Too easy to get', 'Pharmacies, online platforms, wellness clinics, IndiaMART listings (Gadre, Bhargava, MoHFW).'], ['Prescriber limits', 'IMA wants endocrinologists, diabetologists and MD physicians only. MoHFW names endocrinologists, internists and cardiologists.'], ['Supply shocks', 'July recalls disrupted Dr Reddy’s supply until late October.'], ['Generic flood', 'Generics are reshaping demand and prescribing (Mithal). They make up 82% of semaglutide units.']], soWhat: 'Specialists worry about too much access, too loosely. Supply-chain control and prescriber alignment are part of the value story.' },
  'Effect on patients': { points: [['Regain', 'About two-thirds of lost weight returns within a year of stopping (consensus). Misra says 60–70%.'], ['Dropout', 'High discontinuation shows obesity is chronic (Nain). Expectations of drugs alone are unrealistic (Gautam).'], ['Quality of life', 'Weight loss alone doesn’t guarantee better QoL (Misra).'], ['Lifestyle foundation', 'Diet and activity are the base of treatment (Tandon, Iyer, Misra).']], soWhat: 'The 2026 frontier: dropout, regain after stopping, muscle loss. This is the next battleground for evidence and patient support.' },
  'Impact & disease framing': { points: [['Chronic disease', 'OSSI–ESI, cardiology panel and Kular: chronic, relapsing, progressive.'], ['Under-treated', '“We are at a tipping point… yet remains under-treated” (Kalra, OBESITAS).'], ['Legitimate goal', 'Weight loss is a therapeutic goal, not a lifestyle aspiration (Ameya Joshi).'], ['Indian phenotype', 'Lower BMI thresholds and waist cut-offs of 90/80 cm, with India-specific approaches (Pandit).']], soWhat: 'The most positive theme. Societies and cardiologists frame obesity as a chronic disease, and brands can align with that language.' },
  'Appropriate use & misuse': { points: [['Cosmetic demand', 'Brides make up more than 20% of queries (Goel). Requests from people who are only overweight get refused (Arjita Kumar).'], ['Self-medication', 'Quacks, mini-dosing, reckless generic use (Lakdawala, Tandon).'], ['Counselling', 'ESI: counselling before and during therapy. Individualised prescribing (Bhargava).'], ['Gatekeepers', 'IMA’s prescribing memorandum. The MoHFW and CDSCO crackdown.']], soWhat: 'The main reputational risk. Surgeons, diabetologists, AIIMS and IMA act as gatekeepers against cosmetic and unsupervised use.' },
  'Quality & counterfeits': { points: [['Cold chain', 'Peptide manufacturing and cold chain risk batch variation (Kovil).'], ['Recalls', 'Dr Reddy’s, Torrent and USV batches recalled over an API impurity (Jul 2026). Doctors ask for transparency.'], ['Counterfeits', '₹56–70 lakh of fake Mounjaro seized in Gurugram. Risk is high in chronic therapy.'], ['Grey products', 'OTC “oral GLP-1 supplements” sold without data (Indian Practitioner).']], soWhat: 'Small in volume but emotionally loaded, and rising after the July recalls. Transparency and pharmacovigilance build trust.' }
});

export const SPECIALTY_PROFILES = Object.freeze({
  'Endocrinology': 'Set the scientific framing: efficacy, ESI guidelines and Indian real-world data. Increasingly vocal on muscle loss, generic quality and supervised use.',
  'Bariatric & metabolic surgery': 'The largest bloc warning about misuse (brides, mini-dosing, quacks) and the strongest chronic-disease advocates through OSSI. They see drugs as a bridge to, or companion of, surgery.',
  'Diabetology': 'Front-line prescribers. They turn away people who are only overweight and lead the questions on generic cold chain, recalls and manufacturer transparency.',
  'General medicine': 'Physicians and journal editors urge individualised prescribing, flag OTC “oral GLP-1 supplements”, highlight dropout and the cost of lifelong therapy.',
  'Societies & multi-specialty panels': 'Consensus bodies and associations (nutrition consensus, RSSDI, IMA) set protocols: protein targets, counselling and limits on who can prescribe.',
  'Neurology': 'A doctor-creator on X. Pro-prevention and sceptical of weight-loss fads.',
  'Nutrition & dietetics': 'Allied voices warning about rushed titration, GI side effects and unsupervised access. Natural partners for adherence programmes.',
  'Cardiology': 'New entrants (Mar 2026). Call semaglutide practice-changing for CVD with obesity and push waist-based risk criteria for South Asians.',
  'Obstetrics & gynaecology': 'Early adopters for PCOS, reporting menstrual, skin and fertility benefits (off-label).',
  'Obesity clinic': 'Wellness-clinic founders caution against quick-fix demand.'
});

export const WHO_LEDE = 'Endocrinologists (23 statements, net +22) set the scientific framing, backed by ESI guidelines, AIIMS and the Max real-world study. Bariatric surgeons (11, net +27) lead both the misuse warnings and the chronic-disease advocacy. Diabetologists drive the generic-quality debate. Cardiologists, gynaecologists, general physicians, nutritionists and medical associations are new or adjacent voices, and most of the sharpest criticism comes from them.';

export const KEY_VOICES = Object.freeze([
  { who: 'Dr Anoop Misra', tier: 'National KOL' },
  { who: 'Dr Rajiv Kovil', tier: 'National KOL · Media voice' },
  { who: 'Dr Ambrish Mithal', tier: 'National KOL' },
  { who: 'Dr Sudhir Kumar', tier: 'Doctor-creator' },
  { who: 'Dr Amit Bhargava & Dr Varsha Narayanan', tier: 'Hospital specialist' },
  { who: 'Amita Gadre', tier: 'Allied professional' },
  { who: 'Asian Indian nutrition consensus', tier: 'Consensus panel' },
  { who: 'Dr Aparna Govil Bhasker', tier: 'Society leader · OSSI' },
  { who: 'Dr Muffazal Lakdawala', tier: 'National KOL' },
  { who: 'Dr Nikhil Tandon', tier: 'National KOL' },
  { who: 'Dr Preethi Mrinalini', tier: 'Hospital specialist' },
  { who: 'Dr Sachin Mittal', tier: 'Hospital specialist' }
]);

export const CHANNEL_LEDE = 'Specialist opinion reaches the public mainly through journalists and society platforms, not doctors’ own feeds. Promotional clinic content dominates Instagram and marketplaces, while specialist voices stay in news media, conferences and journals. That gap is both a regulatory risk and an opening for responsible brands.';

export const VIDEO_INVENTORY = Object.freeze([
  ['Ozempic, Mounjaro; the Truth About Weight Loss Drugs ft. Dr Ambrish Mithal', 'YouTube · The India Story'],
  ['Exclusive: Dr Ambrish Mithal On India’s Weight Loss Wave: Ozempic, Mounjaro & Magic Pills', 'YouTube · Newshour (recorded news interview)'],
  ['Miracle or Myth? Sneha Mordani Decodes Weight Loss Drugs with Dr Ambrish Mithal | #Booked', 'YouTube · India Today (recorded interview)'],
  ['Not Just Weight Loss: How Ozempic & GLP-1 Drugs Protect Your Heart, Kidneys ft. Dr Ambrish Mithal', 'YouTube'],
  ['Dr Ambrish Mithal backs crackdown on GLP-1 misuse, warns of risks', 'YouTube Shorts'],
  ['The Truth About Weight Loss Drugs | Dr. Ambrish Mithal | EDGE Community', 'YouTube'],
  ['Weight Loss Drugs | Episode 48 | With Dr. Shashank Joshi, Dr. Anil Bhoraskar & Dr Rahul Borude', 'YouTube · doctor podcast'],
  ['Dr.Rajasekhar About Mounjaro: మౌంజారో మంచిదే.. కానీ (“Mounjaro is good… but”)', 'YouTube · BIGTV (Telugu)'],
  ['Weight-Loss Medicines: When and How Doctors use Them', 'MEDtalks · 23 Feb 2026 (English), 26 Feb (Hindi)'],
  ['Obesity Drug Mounjaro Is Now India’s TOP SELLING Medicine: Is It Really A ‘Quick Fix’?', 'YouTube · news deep-dive'],
  ['Weight Loss Drug Wegovy in India: Miracle Cure or Health Risk? | Experts Explain', 'YouTube · news explainer'],
  ['Mounjaro: India’s New Weight Loss & Diabetes ‘Miracle’ | Unmissable With Nabila Jamal', 'YouTube · news show']
]);

export const SOURCE_STATUS = Object.freeze({ CAPTURED: 'Captured', PARTIAL: 'Scanned · partial', NONE: 'Scanned · nothing attributable', RESTRICTED: 'Restricted access' });
export const SOURCE_COVERAGE = Object.freeze([
  { group: 'Social media & communities', rows: [
    ['X (Twitter)', 'CAPTURED', 'Posts from Dr Anoop Misra, Dr Ambrish Mithal and Dr Sudhir Kumar. Also seen: CME INDIA’s recall alert (9 Jul 2026) and investor chatter on the “generic gold rush”.', 5],
    ['LinkedIn', 'RESTRICTED', 'Searched for Indian specialists’ posts. Feeds are login-walled and public posts are barely indexed, so no attributable specialist post was retrieved.', null],
    ['YouTube', 'PARTIAL', '12+ relevant videos: Mithal interviews (India Today, Newshour, The India Story), a Shashank Joshi podcast, Telugu BIGTV, news explainers. Pages were rate-limited, so they are inventoried under Channels.', null],
    ['Instagram', 'RESTRICTED', 'Reels are mostly clinic promotion (e.g., “Mounjaro (Tirzepatide) Now Available in South Delhi”). Blocked by robots rules. Flag: possible surrogate promotion under the Mar 2026 advisory.', null],
    ['Facebook', 'RESTRICTED', 'Publisher posts (India Today on “Mounjaro brides”, The Hindu on patent expiry, a Business Today video). Login-walled, so no specialist statements.', null],
    ['Threads', 'NONE', 'Results were dominated by Malaysian clinic and consumer posts. No Indian specialist content.', null],
    ['Reddit', 'NONE', 'No indexed Indian specialist threads in the window.', null],
    ['Quora', 'NONE', 'Patient-led Q&A (online buying safety, “semaglutide Fitaro” sold in India, generic quality). No verified Indian specialist answers.', null],
    ['Telegram & WhatsApp public channels', 'RESTRICTED', 'Not indexed by search, and most are closed groups. Related signal: open marketplace listings for Mounjaro and tirzepatide on IndiaMART.', null],
    ['ShareChat · Moj · Josh', 'RESTRICTED', 'Not searchable outside the apps. Regional-language signal came from YouTube (Telugu, BIGTV) and Hindi print (Amar Ujala) instead.', null]
  ]},
  { group: 'Video, education & podcasts', rows: [
    ['MEDtalks obesity videos', 'PARTIAL', '20 videos (10 English, 10 Hindi). “Weight-Loss Medicines: When and How Doctors use Them” published 23 Feb 2026. Speaker names are not shown on the listing.', null],
    ['Society & hospital channels, podcasts, recorded interviews', 'PARTIAL', 'Mithal’s interview with Barkha Dutt (shared on X, Aug 2025) plus six YouTube interviews. Joshi, Bhoraskar and Borude podcast (Ep. 48). RSSDI’s 17 public videos cover diabetes, none on obesity drugs.', null]
  ]},
  { group: 'Societies & associations', rows: [
    ['AIAARO', 'NONE', 'President Dr Mahendra Narwaria (bariatric surgery), Hon. Secretary Dr B. M. Makkar (diabetology). AIAAROCON 2026: Guwahati, 11–13 Dec. No public GLP-1 position yet.', null],
    ['OSSI', 'CAPTURED', 'OSSI–ESI joint position statement (Aug 2026). OSSICON 2026 Ahmedabad (25–28 Feb). OSSICON 2027 Hyderabad (Jan).', 4],
    ['Endocrine Society of India', 'CAPTURED', 'ESI obesity guidelines 2025 update (IJEM), Mid-ESICON 2025 Chandigarh, ESI president in the OSSI–ESI consensus.', 3],
    ['RSSDI', 'CAPTURED', 'RSSDI 2025 Kochi obesity track (tirzepatide sessions), IDEJ Feb 2026 GLP-1 articles. No obesity-drug guideline on its guidelines page yet.', 4],
    ['Association of Physicians of India', 'CAPTURED', 'JAPI cardiology consensus on semaglutide (Mar 2026), “Obesity Gurukul” webinar (12 Jul 2025), APICON 2026 Patna.', 2],
    ['IMA (national and chapters)', 'CAPTURED', 'National President Dr Anil Kumar J. Nayak seeks limits on who can prescribe (25 Mar 2026). No chapter-level statements retrieved.', 1],
    ['FOGSI', 'PARTIAL', 'No FOGSI obesity or GLP-1 activity listed. The PCOS angle came from gynaecologists at Motherhood Hospitals (see Hospitals).', null],
    ['IAP', 'PARTIAL', 'IAP childhood obesity guideline (2023). Indian Pediatrics 2026 paper on affordable semaglutide for children identified but not readable (rate-limited).', null],
    ['DiabetesIndia · N-DOC · DFI · ADEI', 'PARTIAL', 'N-DOC and DFI views reached us through Dr Anoop Misra’s media statements. No GLP-1 content on the DiabetesIndia or ADEI public pages.', null]
  ]},
  { group: 'Conferences & CMEs', rows: [
    ['AIAAROCON, OSSICON, ESICON, RSSDI, APICON, PEDICON, FOGSI, CMEs, grand rounds', 'CAPTURED', 'Captured: RSSDI 2025 (Kochi), OBESITAS 2026, Mid-ESICON 2025. APICON, PEDICON and FOGSI meetings had no public GLP-1 content. CMEs and grand rounds are not public.', 5]
  ]},
  { group: 'News & trade media', rows: [
    ['National media (Indian Express, The Hindu, TOI, HT, Mint, India Today, NDTV and others)', 'CAPTURED', 'Captured from Outlook Business, The Tribune, The Week, Business Today, The South First, Esquire, and Indian Express via Dr Mithal’s post. The Hindu (paywalled), TOI, HT, Mint and NDTV gave no new attributable quotes.', 23],
    ['Regional-language papers', 'PARTIAL', 'Amar Ujala (Hindi) on the TGA suicidal-ideation warning (Dec 2025) and the hair-loss study (Sep 2026). No named Indian specialist quotes yet.', null],
    ['International media & wires', 'CAPTURED', 'Reuters, ABC News, Malay Mail (wave 1).', 7],
    ['Medical trade media (Medical Dialogues, ETHealthworld, Express Healthcare and others)', 'CAPTURED', 'Captured from Medical Dialogues (recalls, CDSCO, RSSDI), The Indian Practitioner and OC Academy. ETHealthworld and Express Healthcare returned nothing.', 5]
  ]},
  { group: 'Academic centres & hospitals', rows: [
    ['AIIMS & academic centres', 'CAPTURED', 'AIIMS New Delhi (Dr Nikhil Tandon). KGMU Lucknow (Dr Ambuj Yadav, via RSSDI).', 2],
    ['Hospital blogs & channels (Apollo, Max, Fortis, Medanta, Manipal and others)', 'CAPTURED', 'Captured from Fortis Mohali, Dr Mohan’s (Chennai) and Motherhood Hospitals. Apollo (Apollo 247, Apollo Sugar), Medanta and Manipal pages were service promotion only.', 4]
  ]},
  { group: 'Journals & guidelines', rows: [
    ['PubMed, Indian journals, consensus papers, abstracts', 'CAPTURED', 'IJEM (Max real-world data), Obesity Pillars (nutrition consensus), JAPI, Obesity Surgery (OSSI–ESI). Indian J Psychiatry 2026 metabo-psychiatry paper identified but captcha-blocked.', 3]
  ]}
]);

export const TIMELINE_LEDE = 'Commentary spiked in Q1–Q2 2026, when semaglutide went off patent (20 Mar 2026), the IMA and the health ministry issued warnings, and counterfeit and recall stories broke. It stayed above 2025 levels through Q3 as societies published consensus statements.';

export const EVENTS = Object.freeze([
  ['20 Mar 2025', 'Market', 'Lilly launches Mounjaro (tirzepatide) in India at ₹3,500 for a 2.5 mg vial.'],
  ['1 Jun 2025', 'Society / conference', 'Mid-ESICON 2025 in Chandigarh puts city obesity rates (13.6%) in focus.'],
  ['Jun 2025', 'Market', 'Novo Nordisk launches Wegovy pens in India.'],
  ['12 Jul 2025', 'Society / conference', 'API runs the “Obesity Gurukul” webinar for physicians.'],
  ['26 Aug 2025', 'Scientific', 'ESI obesity guideline update: drug therapy from BMI >27 (or >25 with comorbidity), tirzepatide for 15–20% weight-loss targets.'],
  ['Oct 2025', 'Market', 'Mounjaro becomes India’s top-selling medicine by value. Lilly and Cipla agree to sell tirzepatide as Yurpeak.'],
  ['6–9 Nov 2025', 'Society / conference', 'RSSDI 2025 in Kochi puts obesity and tirzepatide’s dual agonism centre stage.'],
  ['Nov 2025', 'Market', 'Novo cuts Wegovy prices by up to 37%.'],
  ['3 Dec 2025', 'Regulatory', 'Amar Ujala (Hindi) reports Australia’s TGA warning on suicidal ideation and says the drugs are sold freely in India.'],
  ['23 Feb 2026', 'Scientific', 'MEDtalks releases “Weight-Loss Medicines: When and How Doctors use Them” (Hindi version 26 Feb).'],
  ['25–28 Feb 2026', 'Society / conference', 'OSSICON 2026, Ahmedabad: the national bariatric and metabolic surgery meeting.'],
  ['10 Mar 2026', 'Regulatory', 'DCGI/MoHFW advisory: no surrogate promotion; prescription by endocrinologists, internists or cardiologists.'],
  ['16 Mar 2026', 'Scientific', 'National cardiology panel (JAPI) recommends semaglutide for CVD with obesity, with waist cut-offs of 90 cm (men) and 80 cm (women).'],
  ['20 Mar 2026', 'Market', 'Semaglutide patent expires and about 25 generic brands launch, including Dr Reddy’s, Zydus, Sun, Alkem and Glenmark.'],
  ['23 Mar 2026', 'Scientific', 'AIIMS’s Dr Nikhil Tandon: generics are “serious medicines for a serious problem”.'],
  ['25 Mar 2026', 'Regulatory', 'IMA will petition the government to limit GLP-1 prescribing to endocrinologists, diabetologists and MD physicians.'],
  ['Apr 2026', 'Regulatory', 'Counterfeit Mounjaro worth ₹56–70 lakh seized in Gurugram. AIOCD warns of “indiscriminate use.”'],
  ['5 May 2026', 'Society / conference', 'OBESITAS 2026 (IJCP and South Asian Obesity Forum): obesity is “under-treated”.'],
  ['18 May 2026', 'Regulatory', 'CDSCO orders supply-chain surveillance and action on illegal sale and promotion.'],
  ['Jun 2026', 'Market', 'Generic semaglutide momentum fades: value growth falls from 50% in Apr to 6% in May.'],
  ['8–10 Jul 2026', 'Regulatory', 'Dr Reddy’s, Torrent and USV recall selected semaglutide batches after an API impurity finding. Supply disrupted until late October.'],
  ['Jul 2026', 'Scientific', 'Asian Indian nutrition consensus sets protein at 1.2–1.5 g/kg per day and calls for micronutrient monitoring.'],
  ['3 Aug 2026', 'Scientific', 'OSSI–ESI joint position statement: 78 experts, 55 recommendations, no BMI-only treatment decisions.'],
  ['10 Sep 2026', 'Market', 'GLP-1 class reaches ₹2,333 cr MAT. Mounjaro ₹1,256 cr (+502%).'],
  ['14 Sep 2026', 'Regulatory', 'Amar Ujala (Hindi) covers a new study linking GLP-1 drugs to hair-loss risk.'],
  ['11–13 Dec 2026', 'Society / conference', 'Coming up: AIAAROCON 2026, Guwahati. Worth monitoring in the next wave.'],
  ['Context', 'Scientific', 'STAT op-ed: 43% of Indian adults are metabolically obese at BMI below 25, so label BMI cut-offs miss them.']
].map(([date, type, text]) => ({ date, type, text })));

export const MARKET = Object.freeze({
  lede: 'Secondary data from Pharmarack and published prices, so the listening findings can be read against the market. These figures are not part of the sentiment corpus.',
  kpis: [['₹2,333 cr', 'GLP-1 class, 12 months to Aug 2026'], ['₹1,256 cr', 'Mounjaro, same period (+502% YoY)'], ['~62%', 'Tirzepatide share of class value'], ['82%', 'Generic share of semaglutide units (Jul 2026)']],
  classMat: [['Apr 2022', 121], ['Mar 2026', 1579], ['Apr 2026', 1736], ['Aug 2026', 2333]],
  costRanges: [['Mounjaro (tirzepatide)', 13125, 25781], ['Wegovy (semaglutide)', 5660, 16400], ['Generic semaglutide', 1200, 8000]],
  genericShare: [['Torrent', 38], ['Zydus', 10], ['Lupin', 9], ['Dr Reddy’s', 8], ['Eris', 8], ['Alkem', 8], ['Others', 19]],
  genericNote: 'Share of generic semaglutide value (combined ₹44 cr in April). Torrent led within four weeks of launch. Dr Reddy’s, Torrent and USV recalled selected batches in July 2026.'
});

export const TEAM_ACTIONS = Object.freeze({
  'Brand': [
    ['No specialist disputes efficacy. They quote 15–22% loss and CV and renal benefit.', 'Stop leading with efficacy alone.', 'Differentiate on what specialists now question: lean-mass preservation, maintenance, CV and renal outcomes, and QoL, backed by Indian data.'],
    ['Misuse is the most discussed theme: brides, mini-dosing, quacks, “reckless” generic use, clinic promotion on Instagram.', 'Own the responsible-use position.', 'Build trust around patient selection and supervised titration. Stay out of influencer and surrogate content that MoHFW and CDSCO now police.'],
    ['Recalls (Jul 2026), counterfeits and cold-chain doubts. Diabetologists demand transparency.', 'Make quality visible.', 'Batch transparency, cold-chain assurance, pack authentication and quick HCP communication when issues arise.'],
    ['The IMA seeks prescriber limits. Societies are writing protocols.', 'Align with the gatekeepers.', 'Prioritise endocrinologists, diabetologists and MD physicians, and support ESI, OSSI and RSSDI protocols rather than broad DTC-style awareness.']
  ],
  'Product & marketing': [
    ['Dropout, GI side effects and rushed titration are the most-cited reasons treatment fails.', 'Launch a persistence programme:', 'titration guides, GI management kits, protein and micronutrient coaching (1.2–1.5 g/kg per day), and expectation-setting at the first prescription.'],
    ['Specialists reach the public through journalists, conferences and society publications. Doctor-creators are few.', 'Invest in earned medical media and society platforms', '(RSSDI, ESI, OSSI, API, AIAAROCON Dec 2026). Brief health journalists with specialist spokespeople.'],
    ['Regional signals (Hindi, Telugu) are rising, while closed platforms (WhatsApp, ShareChat) can’t be monitored openly.', 'Localise responsibly.', 'Regional-language HCP education, and a monitored listening panel for closed channels in the next wave.'],
    ['New specialty voices: cardiology (Mar 2026), gynaecology and PCOS, general physicians on cost.', 'Re-segment targeting.', 'A cardiometabolic stream for cardiologists, evidence-led PCOS dialogue, and bariatric surgeons as combination-care partners.']
  ],
  'Scientific & medical affairs': [
    ['Muscle is 25–35% of weight lost. Sarcopenia is common in Indians. Micronutrient deficits rise.', 'Generate Indian body-composition RWE', '(DEXA or BIA) and publish nutrition protocols built for Indian diets.'],
    ['About two-thirds of weight regained within a year of stopping. High dropout.', 'Study maintenance:', 'dose tapering, persistence drivers and structured post-therapy support in Indian cohorts.'],
    ['Max real-world data shows tirzepatide ahead of semaglutide. BMI and waist cut-offs miss Indian patients.', 'Build the Asian Indian phenotype evidence base', 'for label, guideline and reimbursement discussions at lower BMI with comorbidity.'],
    ['API impurity recalls, psychiatric and hair-loss signals in the media.', 'Strengthen pharmacovigilance and stability data', 'under Indian distribution conditions, and share proactively with KOLs and societies.']
  ]
});

export const METHOD = Object.freeze([
  ['Scope and collection', [
    'Public statements by named Indian HCPs, hospitals and specialist societies on obesity pharmacotherapy, Mar 2025 to Sep 2026.',
    'Wave 2 added searches across X, LinkedIn, YouTube, Instagram, Facebook, Threads, Reddit, Quora, Telegram and WhatsApp channels, ShareChat, Moj and Josh, MEDtalks, society sites (AIAARO, OSSI, ESI, RSSDI, API, IMA, FOGSI, IAP), conferences, national, regional and trade media, hospital blogs, and journals.',
    'A statement is kept only when it can be attributed to a person, institution or panel with a known specialty. Wave 1 statements are kept unchanged.'
  ]],
  ['Coding', [
    'Themes: efficacy, safety and tolerability, cost, availability and access, effect on patients, impact and disease framing, appropriate use and misuse, quality and counterfeits.',
    'Sentiment: stance toward GLP-1 therapy as used today. Positive = endorsing, negative = warning or critical, mixed = balanced or neutral. Coded by an analyst, not a model score.',
    'Framing: advocacy, education, caution, gatekeeping, market commentary.'
  ]],
  ['Limitations', [
    'Closed or login-walled platforms (WhatsApp and Telegram groups, Instagram, Facebook, LinkedIn feeds, ShareChat, Moj, Josh) could not be collected automatically. See the source coverage table.',
    'YouTube pages were rate-limited, so videos are inventoried by title. The Indian Pediatrics semaglutide paper and the Indian Journal of Psychiatry paper were identified but could not be read.',
    'With under 100 statements, read shares as directional, not statistically representative.',
    'Quotes appear as published. Where only a phrase was available, the rest is paraphrased and marked.',
    'Every source was re-opened and each quote checked against the page. Five X posts are matched on search-indexed text because X blocks automated reading.'
  ]]
]);

// ---------- Derived views (pure functions, shared by UI and tests) ----------
export const netOf = rows => rows.length ? Math.round((rows.filter(r => r.sentiment === 'Positive').length - rows.filter(r => r.sentiment === 'Negative').length) / rows.length * 100) : 0;
export const splitOf = rows => SENTIMENTS.map(s => rows.filter(r => r.sentiment === s).length);
export const quarterOf = iso => { const y = +iso.slice(0, 4), m = +iso.slice(5, 7); return `${y} Q${Math.floor((m - 1) / 3) + 1}`; };
export const QUARTERS = Object.freeze(['2025 Q1', '2025 Q2', '2025 Q3', '2025 Q4', '2026 Q1', '2026 Q2', '2026 Q3']);

export function groupBy(rows, key) {
  const map = new Map();
  for (const r of rows) for (const k of [].concat(typeof key === 'function' ? key(r) : r[key])) { if (!map.has(k)) map.set(k, []); map.get(k).push(r); }
  return map;
}
export function filterStatements(rows, f = {}) {
  const q = (f.query || '').trim().toLowerCase();
  return rows.filter(r => (!f.specialty || r.specialty === f.specialty) && (!f.theme || r.themes.includes(f.theme)) && (!f.channel || r.channel === f.channel) && (!f.sentiment || r.sentiment === f.sentiment) && (!f.period || r.date.startsWith(f.period)) && (!q || `${r.who} ${r.role} ${r.text} ${r.source} ${r.specialty}`.toLowerCase().includes(q)));
}
export function themeShift(rows) {
  const a = rows.filter(r => r.date.startsWith('2025')), b = rows.filter(r => r.date.startsWith('2026'));
  const share = (set, t) => set.length ? set.filter(r => r.themes.includes(t)).length / set.length * 100 : 0;
  return THEMES.map(({ name }) => ({ name, y2025: share(a, name), y2026: share(b, name), n2025: a.filter(r => r.themes.includes(name)).length, n2026: b.filter(r => r.themes.includes(name)).length, delta: Math.round(share(b, name) - share(a, name)) }));
}

// Source pages, located by search and checked against the quoted text on 28 Sep 2026.
// check: 'page' = quote read on the fetched page; 'index' = X post matched on search-indexed text (X blocks automated reading).
export const SOURCE_LINKS = Object.freeze({
  'Indian Pharma Post on OSSI–ESI consensus, Aug 2026': { url: 'https://www.indianpharmapost.com/healthcare/ossiesi-consensus-calls-for-personalised-stigma-free-obesity-care-in-india-21489', check: 'page', published: '21 Aug 2026' },
  'The South First on Asian Indian nutrition consensus, 21 Jul 2026': { url: 'https://thesouthfirst.com/bold/muscle-loss-and-nutrient-deficiencies-indias-first-glp-1-guidance-on-the-cost-of-weight-loss/', check: 'page', published: '21 Jul 2026' },
  'X · @docanoopmisra, 13 Jul 2026': { url: 'https://x.com/docanoopmisra/status/2076609295706456440', check: 'index', published: '13 Jul 2026', note: 'Post promotes his Indian Express article.' },
  'Medical Dialogues on semaglutide recalls, 10 Jul 2026': { url: 'https://medicaldialogues.in/news/industry/pharma/recalls-by-dr-reddys-torrent-put-spotlight-on-quality-standards-in-indias-semaglutide-market-174725', check: 'page', published: '10 Jul 2026', note: 'Medical Dialogues credits India Today for the quote.' },
  'Outlook Business, 29 Jun 2026': { url: 'https://www.outlookbusiness.com/corporate/the-glp-1-gold-rush-is-over-why-indias-generic-semaglutide-market-is-losing-momentum', check: 'page', published: '29 Jun 2026' },
  'ABC News, 10 May 2026': { url: 'https://www.abc.net.au/news/2026-05-10/india-embraces-weight-loss-drugs-but-doctors-are-concerned/106544560', check: 'page', published: '10 May 2026' },
  'Business Today, 6 May 2026': { url: 'https://www.businesstoday.in/industry/pharma/story/here-are-the-risks-of-weight-loss-drugs-that-doctors-want-you-to-know-530032-2026-05-06', check: 'page', published: '6 May 2026' },
  'Indian Pharma Post on OBESITAS 2026, 5 May 2026': { url: 'https://www.indianpharmapost.com/healthcare/obesitas-2026-concludes-with-focus-on-indias-rising-obesity-burden-20060', check: 'page', published: '5 May 2026' },
  'Motherhood Hospitals media coverage, May 2026': { url: 'https://www.motherhoodindia.com/mediacoverage/glp1-drugs-for-pcos-india-benefits-risks-fertility-treatment-trend/', check: 'page', published: 'May 2026', note: 'Hospital’s own coverage page; the original outlet is not named.' },
  'The Week, 30 Apr 2026': { url: 'https://www.theweek.in/news/health/2026/04/30/counterfeit-mounjaro-seizure-in-gurugram-raises-fresh-concerns-over-fake-drugs-market.html', check: 'page', published: '30 Apr 2026' },
  'X · @DrAmbrishMithal, 25 Apr 2026': { url: 'https://x.com/DrAmbrishMithal/status/2047997228602822760', check: 'index', published: '25 Apr 2026', note: 'Quotes an Indian Express report by Ankita Upadhay.' },
  'Indian J Endocrinol Metab (Max Healthcare real-world study), 6 Apr 2026': { url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC13229245/', check: 'page', published: '6 Apr 2026' },
  'Malay Mail / Reuters, 4 Apr 2026': { url: 'https://www.malaymail.com/news/life/2026/04/04/mounjaro-brides-trend-takes-off-as-indias-wedding-industry-meets-weight-loss-injections/214945', check: 'page', published: '4 Apr 2026' },
  "Dr. Mohan's Diabetes Specialities Centre blog, 1 Apr 2026": { url: 'https://drmohans.com/weight-loss-injections-safety/', check: 'page', published: '1 Apr 2026' },
  'ANI, 25 Mar 2026': { url: 'https://aninews.in/news/national/general-news/any-modern-medicine-taken-without-prescription-can-be-dangerous-ima-warns-against-misuse-of-weight-loss-drugs-seeks-stronger-regulation20260325223110/', check: 'page', published: '25 Mar 2026' },
  'The Week, 24 Mar 2026': { url: 'https://www.theweek.in/news/health/2026/03/24/will-generic-semaglutide-make-diabetes-and-weight-loss-treatment-more-accessible-in-india.html', check: 'page', published: '24 Mar 2026' },
  "ANI via India's News, 23 Mar 2026": { url: 'https://www.indiasnews.net/news/278939836/weight-loss-drugs-serious-medicines-for-serious-problem-shouldnt-be-used-recklessly-warns-aiims-expert', check: 'page', published: '23 Mar 2026' },
  'OC Academy, 23 Mar 2026': { url: 'https://www.ocacademy.in/blogs/generic-semaglutide-india-caution/', check: 'page', published: '23 Mar 2026' },
  'The South First on JAPI cardiology consensus, 16 Mar 2026': { url: 'https://thesouthfirst.com/bold/semaglutide-ozempic-for-heart-patient/', check: 'page', published: '16 Mar 2026' },
  'Fortis Healthcare blog, 13 Mar 2026': { url: 'https://www.fortishealthcare.com/blogs/obesity-control-options-2026-apps-metabolic-bariatric-surgery', check: 'page', published: '13 Mar 2026' },
  'The Indian Practitioner, Mar 2026': { url: 'https://theindianpractitioner.com/glp1-ra-and-weight-loss-boom-in-india-trends-concerns-and-caution-dr-amit-bhargava-dr-varsha-narayanan/', check: 'page', published: 'Mar 2026' },
  'RSSDI IDEJ newsletter, Issue 131, Feb 2026': { url: 'https://www.rssdi.in/newwebsite/pdfdata/IDEJ/2026/IDEJ_Issue-No-131-February-2026.pdf', check: 'page', published: 'Feb 2026' },
  'Reuters (syndicated), 23 Dec 2025': { url: 'https://www.investing.com/news/stock-market-news/lilly-novo-lock-horns-in-indias-obesity-drug-race-4422180', check: 'page', published: '23 Dec 2025', note: 'Reuters story as syndicated by Investing.com.' },
  'Outlook Business, 20 Dec 2025': { url: 'https://www.outlookbusiness.com/health/social-media-doctors-are-driving-indians-to-weight-loss-drugs-like-mounjaro-wegovy-its-illegal', check: 'page', published: '20 Dec 2025' },
  'Esquire India, 18 Dec 2025': { url: 'https://www.esquireindia.co.in/lifestyle/health-and-wellness/dr-muffazal-lakdawala-on-treating-obesity-without-shame', check: 'page', published: '18 Dec 2025' },
  'Medical Dialogues on RSSDI 2025 obesity track': { url: 'https://medicaldialogues.in/diabetes-endocrinology/obesity-discussions-to-take-spotlight-at-rssdi-2025-experts-to-delve-into-tirzepatides-dual-agonism-in-metabolic-care-158048', check: 'page', published: '4 Nov 2025', note: 'Conference-preview wording, not attributed to a named speaker.' },
  'ESI Clinical Practice Guidelines for Obesity – 2025 update (IJEM, PMC)': { url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC12410957/', check: 'page', published: '26 Aug 2025' },
  'X · @DrAmbrishMithal, 18 Aug 2025': { url: 'https://x.com/DrAmbrishMithal/status/1957287382748664127', check: 'index', published: '18 Aug 2025' },
  'The Tribune, 29 Jun 2025': { url: 'https://www.tribuneindia.com/news/features/weighing-in-on-weight-loss-drugs/', check: 'page', published: '29 Jun 2025' },
  'X · @hyderabaddoctor, 25 Jun 2025': { url: 'https://x.com/hyderabaddoctor/status/1937857246689685739', check: 'index', published: '25 Jun 2025' },
  'The Tribune on Mid-ESICON 2025, 1 Jun 2025': { url: 'https://www.tribuneindia.com/news/chandigarh/at-13-6-chandigarh-among-top-cities-in-obesity-experts-at-mid-esicon-2025/', check: 'page', published: '1 Jun 2025' },
  'The South First, 25 Mar 2025': { url: 'https://thesouthfirst.com/health/obesity-diabetes-injection-in-india-a-lifesaver-or-just-another-quick-fix/', check: 'page', published: '25 Mar 2025' },
  'X · @hyderabaddoctor, 5 Mar 2025': { url: 'https://x.com/hyderabaddoctor/status/1897141903130542558', check: 'index', published: '5 Mar 2025', note: 'Post links a News9 article that cites him.' }
});
export const sourceLink = label => SOURCE_LINKS[label] || null;
