// Individual current-practice reviews. Former employment and training are excluded.
const maxReviews = [
  ['dr-prachi-jain-rai', ['Lucknow'], 'Named cardiology team entry on official Lucknow hospital page', 'https://www.maxhealthcare.in/lucknow/hospital/best-cardiology-hospital-lucknow'],
  ['dr-priyamvada-tyagi', ['New Delhi', 'Noida'], 'Max Patparganj appointment location; named doctor and clinic address at Sushrut Healthcare, Sector 45 Noida'],
  ['dr-saket-kant', ['New Delhi'], 'Current appointment location: Max Shalimar Bagh'],
  ['dr-anand-ratan', ['Noida'], 'Named Internal Medicine consultant on official Sector 128 Noida doctor directory', 'https://www.maxhealthcare.in/doctor/sector-128-noida?page=3'],
  ['dr-jeevan-aggarwal', ['New Delhi'], 'Named Internal Medicine doctor on official Shalimar Bagh hospital roster', 'https://www.maxhealthcare.in/hospital-network/max-super-speciality-hospital-shalimar-bagh'],
  ['dr-prem-narayan-vaish', ['Dehradun'], 'Named physician clinic page lists Max Hospital, Rajpur Road, Dehradun', 'https://premnarayan.personal.clinic/'],
  ['dr-rommel-tickoo', ['New Delhi'], 'Current appointment locations and OPD schedules: Saket and Panchsheel Park'],
  ['dr-s-k-das', ['New Delhi'], 'Named Internal Medicine doctor card appointment hospital: Max Saket', 'https://www.maxhealthcare.in/saket/hospital/best-heavy-bleeding-hospital-saket'],
  ['dr-priyanka-chauhan-garg', ['Dehradun'], 'Current appointment location: Max Dehradun'],
  ['dr-suman-lal', ['Gurugram'], 'Current appointment location: Max Hospital Gurgaon'],
  ['dr-atul-singh-rajput', ['Nagpur'], 'Exact name and cardiology role in official directory; appointment Hospital field is max-super-speciality-hospital-nagpur', 'https://www.maxhealthcare.in/find-a-doctor?page=28'],
  ['dr-pankaj-kumar-singh', ['Lucknow'], 'Exact name and interventional cardiology role; official doctor card appointment Hospital field is max-super-speciality-hospital-lucknow', 'https://www.maxhealthcare.in/doctor/interventional-cardiologist-in-lucknow'],
  ['dr-punish-sadana-1', ['Dehradun','Saharanpur'], 'Current practice FAQ and OPD schedules: Max Dehradun and Max Med Centre Saharanpur'],
  ['dr-dilish-malik', ['New Delhi'], 'Current appointment location and FAQ: Max Panchsheel Park'],
  ['dr-kush-ohri', ['Ghaziabad'], 'Exact name and internal medicine role; official appointment Hospital field is max-super-speciality-hospital-vaishali', 'https://www.maxhealthcare.in/cps/best-erectile-dysfunction-doctors?page=5'],
  ["dr-vandana-boobna",["New Delhi"],"Current appointment location: Max Shalimar Bagh"],
  ["dr-vandana-malhotra-goel",["Noida"],"Current appointment location: Max Sector 128 Noida"],
  ["dr-alka-gujral",["New Delhi"],"Current appointment location: Max Smart Saket and Panchsheel Park"],
  ["alka-sinha",["New Delhi"],"Current appointment location: BLK Max, New Delhi"],
  ["saloni-arora",["New Delhi"],"Current appointment location: BLK Max and Shalimar Bagh"],
  ["dr-shashi-kumar",["Noida"],"Current appointment location: Max Sector 128 Noida"],
  ["dr-shruti-bhatia",["New Delhi"],"Current appointment location: BLK Max"],
  ["dr-suruchi-desai",["Mumbai"],"Current appointment location: Nanavati Max Mumbai"],
  ["tripti-sharan",["New Delhi"],"Current appointment location: BLK Max, New Delhi"],
  ["dr-uddhavraj-dudhedia",["Mumbai"],"Current appointment location: Nanavati Max Mumbai"],
  ["uma-rani",["New Delhi"],"Current appointment location: BLK Max, New Delhi"],
  ["dr-kanchan-gadkari",["Mumbai"],"Current appointment location: Nanavati Max Mumbai"],
  ["dr-manoj-ranka",["New Delhi"],"Current appointment location: Saket, Panchsheel Park and Lajpat Nagar"],
  ["dr-nilesh-dharurkar",["Mumbai"],"Current appointment location: Nanavati Max Mumbai"],
  ["dr-nitin-rathod",["Mumbai"],"Current appointment location: Nanavati Max Mumbai"],
  ["dr-pankaj-chaudhary",["Ghaziabad"],"Current appointment location: Max Vaishali"],
  ["dr-rahul-tambe",["Mumbai"],"Current appointment location: Nanavati Max Mumbai"],
  ["dr-skarora",["New Delhi"],"Current appointment location: Max Shalimar Bagh"],
  ["dr-shirang-sanglikar",["Mumbai"],"Current appointment location: Nanavati Max Mumbai"],
  ["sumit-sethi-medicine",["New Delhi"],"Current appointment location: Max Saket"],
  ["dr-sunil-verma",["Lucknow"],"Current appointment location: Max Lucknow"],
  ["dr-swadesh-kumar-singh",["Lucknow"],"Current appointment location: Max Lucknow"],
  ["dr-tushar-bidhuri",["Noida"],"Current appointment location: Max Sector 128 Noida"],
  ["dr-ajay-shukla",["Lucknow"],"Current appointment location: Max Lucknow"],
  ["dr-jayant-vishwanath-kelwade",["Nagpur"],"Current appointment location: Max Nagpur"],
  ["dr-mihir-raut",["Mumbai"],"Current appointment location: Nanavati Max Mumbai"],
  ["dr-suresh-sawardekar",["Mumbai"],"Current appointment location: Nanavati Max Mumbai"],
  ["dr-aditya-bhatla",["Noida"],"Current appointment location: Max Sector 128 Noida"],
  ["dr-deepali-mohanty",["Lucknow"],"Current appointment location: Max Lucknow"],
  ["dr-gaurav-bhalla",["New Delhi"],"Current appointment location: Max Shalimar Bagh"],
  ["dr-harshad-limaye",["Mumbai"],"Current appointment location: Nanavati Max Mumbai"],
  ["dr-hemalata-arora",["Mumbai"],"Current appointment location: Nanavati Max Mumbai"],
  ["dr-hridaya-nath-tripathi",["Lucknow"],"Current appointment location: Max Lucknow"],
  ["dr-jyoti-jain",["Noida"],"Current appointment location: Max Sector 128 Noida"],
  ["dr-ashish-kumar-govil",["Noida"],"Current appointment location: Max Sector 128 Noida"],
  ["dr-b-l-agarwal",["Noida"],"Current appointment location: Max Sector 128 Noida"],
  ["dr-dheeraj-kumar-gandotra",["New Delhi"],"Current appointment location: BLK Max and Max Dwarka"],
  ["dr-h-k-agarwal",["New Delhi"],"Current appointment location: Max Saket"],
  ["dr-harish-mohanty",["Mumbai"],"Current appointment location: Nanavati Max, Mumbai"],
  ["dr-naveen-bhamri",["New Delhi"],"Current appointment location: BLK Max and Shalimar Bagh"],
  ["dr-pushkraj-shamsunder-gadkari",["Nagpur"],"Current appointment location: Max Nagpur"],
  ["dr-salil-shirodkar",["Mumbai"],"Current appointment location: Nanavati Max, Mumbai"],
  ["subhash-chandra",["New Delhi"],"Current appointment location: BLK Max"],
  ["dr-sunil-sofat",["Noida"],"Current appointment location: Max Sector 128 Noida"],
  ["dr-sushant-patil",["Mumbai"],"Current appointment location: Nanavati Max, Mumbai"],
  ["dr-t-s-kler",["New Delhi","Gurugram","Mohali"],"Current appointment location: BLK Max; selector also lists Gurugram and Mohali"],
  ["dr-sonia-naik",["New Delhi"],"Current practice FAQ: Max Smart Saket and Panchsheel Park"],
  ["dr-sowjanya-aggarwal",["Ghaziabad"],"Current practice FAQ: Vaishali"],
  ["dr-swasti",["Ghaziabad","New Delhi"],"Current practice FAQ: Vaishali and Patparganj"],
  ["dr-swati-mittal",["New Delhi"],"Current practice FAQ: Shalimar Bagh"],
  ["dr-teena-singh",["Gurugram"],"Current practice FAQ: Gurgaon"],
  ["dr-tushar-agarwal",["Dehradun"],"Current practice FAQ: Dehradun"],
  ["dr-usha-maurya-kumar",["New Delhi"],"Current practice FAQ: Max Smart Saket"],
  ["dr-usha-upreti",["New Delhi"],"Current practice FAQ: Patparganj"],
  ["dr-vibha-bansal",["Noida"],"Current practice FAQ: Sector 19 Noida"],
  ["dr-yashica-gudesar",["New Delhi"],"Current practice FAQ: Dwarka"],
  ["dr-rashmi-varshney-gupta",["Dehradun"],"Current practice FAQ: Dehradun"],
  ["dr-ritu-sethi",["Gurugram"],"Current practice FAQ: Gurgaon"],
  ["dr-sn-basu",["New Delhi"],"Current practice FAQ: Shalimar Bagh, Delhi"],
  ["dr-santosh-kumari",["New Delhi"],"Current practice FAQ: Patparganj"],
  ["dr-saswati-maiti",["New Delhi"],"Current practice FAQ: Max Smart Saket"],
  ["dr-seema-bhardwaj",["New Delhi"],"Current practice FAQ: Shalimar Bagh"],
  ["dr-seema-jain",["New Delhi"],"Current practice FAQ: Shalimar Bagh"],
  ["dr-seema-wadhwa",["Mohali"],"Current practice FAQ: Mohali"],
  ["dr-shalini-singh",["New Delhi"],"Current practice FAQ: Panchsheel Park"],
  ["dr-shaveta-gupta",["Mohali"],"Current practice FAQ: Mohali"],
  ["dr-shilpa-ghosh",["New Delhi"],"Current practice FAQ: Dwarka"],
  ["dr-shipra-bahuguna-gaur",["Dehradun"],"Current practice FAQ: Dehradun"],
  ["dr-shipra-gupta",["New Delhi"],"Current practice FAQ: Shalimar Bagh, Pitampura and Patparganj"],
  ["dr-shraddha-pradhan-sayana",["Dehradun"],"Current practice FAQ: Dehradun"],
  ["dr-shubha-gupta",["Ghaziabad"],"Current practice FAQ: Vaishali"],
  ["dr-shweta",["Ghaziabad"],"Current practice FAQ: Vaishali"],
  ["dr-supriya-bali",["New Delhi"],"Current practice FAQ: Panchsheel Park, Saket and Lajpat Nagar"],
  ["dr-suresh-chandra",["Noida"],"Current practice FAQ: Sector 19 Noida"],
  ["dr-vaibhav-rohatgi",["New Delhi"],"Current practice FAQ: Panchsheel Park"],
  ["dr-vandana-garg",["Noida","Ghaziabad"],"Current practice FAQ: Noida and Vaishali"],
  ["dr-vimal-kumar-nakra",["New Delhi"],"Current practice FAQ: Patparganj"],
  ["dr-viresh-p-mehta",["New Delhi"],"Current practice FAQ: Patparganj"],
  ["dr-vivek-pal-singh",["New Delhi"],"Current practice FAQ: BLK Max"],
  ["prof-dr-uma-rai",["Noida"],"Current practice FAQ: Noida"],
  ["dr-aarti-puri",["Noida"],"Current practice FAQ: Noida"],
  ["dr-devavrat-arya",["New Delhi"],"Current practice FAQ: Lajpat Nagar and Saket"],
  ["dr-jyoti-raina",["Dehradun"],"Current practice FAQ: Dehradun"],
  ["dr-luna-pant",["Dehradun"],"Current practice FAQ: Dehradun"],
  ["dr-meenu-walia",["Ghaziabad","Noida","New Delhi"],"Current practice FAQ: Vaishali, Noida and Patparganj"],
  ["dr-ravi-kant-behl",["Mohali"],"Current practice FAQ: Mohali"],
  ["dr-ritesh-gupta",["Noida"],"Current practice FAQ: Noida"],
  ["dr-ritu-malani",["New Delhi"],"Current practice FAQ: Panchsheel Park and Saket"],
  ["dr-rumana-aziz",["New Delhi"],"Current practice FAQ: Panchsheel Park, New Delhi"],
  ["dr-s-k-bakshi",["New Delhi"],"Current practice FAQ: Max Smart Saket and Panchsheel Park"],
  ["dr-s-k-sahoo",["Noida"],"Current practice FAQ: Noida"],
  ["dr-sanjay-dhall",["New Delhi"],"Current practice FAQ: Shalimar Bagh"],
  ["dr-sanjay-sanadhya",["Noida"],"Current practice FAQ: Sector 128 Noida"],
  ["dr-sehba-asim-nehal",["Nagpur"],"Current practice FAQ: Nagpur"],
  ["dr-shailesh-sahay",["Gurugram"],"Current practice FAQ: Gurugram"],
  ["dr-sharmistha-sarangi",["Bhubaneswar"],"Current practice FAQ: Bhubaneswar"],
  ["dr-shilpi-manchanda",["Lucknow"],"Current practice FAQ: Lucknow"],
  ["dr-shivam-sharma",["Gurugram"],"Current practice FAQ: Gurugram"],
  ["dr-shweta-s-acharya",["New Delhi"],"Current practice FAQ: Max Smart Saket"],
  ["dr-sumit-khetarpal",["Mohali"],"Current practice FAQ: Mohali"],
  ["dr-nishesh-jain",["Ghaziabad"],"Current practice FAQ: Vaishali"],
  ["dr-nitin-vitthalrao-dambhare",["Nagpur"],"Current practice FAQ: Nagpur"],
  ["dr-pankaj-relan",["Ghaziabad"],"Current practice FAQ: Vaishali"],
  ["dr-pankaj-soni",["New Delhi"],"Current practice FAQ: Max Smart Saket"],
  ["dr-parinita-kaur",["New Delhi"],"Current practice FAQ: Dwarka"],
  ["dr-parul-kakkar",["New Delhi"],"Current practice FAQ: Shalimar Bagh"],
  ["dr-pooja-garg",["New Delhi"],"Current practice FAQ: Patparganj"],
  ["dr-prabhat-ranjan-sinha",["New Delhi"],"Current practice FAQ: Dwarka"],
  ["dr-pratima-verma",["New Delhi"],"Current practice FAQ: Panchsheel Park"],
  ["dr-priyanka-gaur",["Noida"],"Current practice FAQ: Noida"],
  ["dr-r-s-mishra",["New Delhi"],"Current practice FAQ: Max Smart Saket"],
  ["dr-rajeev-kapur",["New Delhi"],"Current practice FAQ: Panchsheel Park"],
  ["dr-rajendra-singh",["New Delhi"],"Current practice FAQ: Dwarka"],
  ["dr-rajinder-kumar-singal",["New Delhi"],"Current practice FAQ: BLK Max"],
  ["dr-rajiv-dang",["Gurugram"],"Current practice FAQ: Gurgaon"],
  ["dr-rajneesh-c-shrivastava",["Gurugram"],"Current practice FAQ: Gurgaon"],
  ["kunal-gupta",["New Delhi"],"Current practice FAQ: Patparganj"],
  ["dr-lkc-sinha",["New Delhi"],"Current practice FAQ: Patparganj"],
  ["dr-lakhwinder-singh-kang",["Mohali"],"Current practice FAQ: Mohali"],
  ["dr-manish-gaba",["New Delhi"],"Current practice FAQ: Max Smart Saket"],
  ["dr-manish-mathur",["New Delhi"],"Current practice FAQ: Shalimar Bagh"],
  ["dr-manoj-kumar-gupta",["Noida"],"Current practice FAQ: Noida"],
  ["dr-mansi-nigam",["Noida"],"Current practice FAQ: Noida"],
  ["dr-mayank-anand",["New Delhi"],"Current practice FAQ: Patparganj"],
  ["dr-meenakshi-jain",["Noida","New Delhi"],"Current practice FAQ: Noida and Patparganj"],
  ["dr-monica-mahajan",["New Delhi"],"Current practice FAQ: Panchsheel Park, Saket and Lajpat Nagar"],
  ["dr-mukesh-mehra",["New Delhi"],"Current practice FAQ: Patparganj"],
  ["dr-n-m-agarwal",["New Delhi"],"Current practice FAQ: BLK Max"],
  ["dr-namrita-singh",["New Delhi"],"Current practice FAQ: Max Smart Saket and Panchsheel Park"],
  ["dr-naresh-dang",["New Delhi"],"Current practice FAQ: Patparganj"],
  ["dr-neelima-mishra",["Gurugram"],"Current practice FAQ: Gurgaon"],
  ["dr-neeti-pravesh",["New Delhi"],"Current practice FAQ: Shalimar Bagh"],
  ["dr-deepak-gargi-pande",["New Delhi"],"Current practice FAQ: BLK Max"],
  ["dr-dinesh-srivastava",["New Delhi"],"Current practice FAQ: Panchsheel Park, Delhi"],
  ["dr-divya-garg",["Dehradun"],"Current practice FAQ: Dehradun"],
  ["dr-gagan-anand",["New Delhi"],"Current practice FAQ: BLK Max"],
  ["dr-gita-prakash",["New Delhi"],"Current practice FAQ: Panchsheel Park"],
  ["dr-gurpreet-singh-babra",["Mohali"],"Current practice FAQ: Mohali"],
  ["dr-hans-raj",["New Delhi"],"Current practice FAQ: Panchsheel Park"],
  ["dr-hari-kumar-yadav",["New Delhi"],"Current practice FAQ: Max Smart Saket"],
  ["dr-hitesh-punyani",["New Delhi"],"Current practice FAQ: BLK Max, New Delhi"],
  ["dr-jay-kirtani",["New Delhi"],"Current practice FAQ: Panchsheel Park and Saket, New Delhi"],
  ["dr-jeevanjyot-bahina",["New Delhi"],"Current practice FAQ: BLK Max"],
  ["dr-kamal-kishore-karnani",["New Delhi"],"Current practice FAQ: Pitampura"],
  ["dr-col-adnan-masood",["Dehradun"],"Current practice FAQ: Dehradun"],
  ["dr-ajay-kumar-gupta",["Ghaziabad"],"Current practice FAQ: Vaishali"],
  ["dr-akash-garg",["Noida"],"Current practice FAQ: Noida"],
  ["dr-alex-mathew",["New Delhi"],"Current practice FAQ: Patparganj"],
  ["dr-amrit-singh-matharu",["New Delhi"],"Current practice FAQ: Patparganj"],
  ["dr-anil-motta",["New Delhi"],"Current practice FAQ: Patparganj"],
  ["dr-anil-vardani",["New Delhi"],"Current practice FAQ: BLK Max"],
  ["dr-ankit-tuteja",["New Delhi"],"Current practice FAQ: Dwarka"],
  ["dr-ankita-sharma",["Noida"],"Current practice FAQ: Sector 19, Noida"],
  ["dr-anuj-s-tiwari",["Mumbai"],"Current practice FAQ: Nanavati Max, Mumbai"],
  ["dr-arun-dewan",["New Delhi"],"Current practice FAQ: Max Smart Saket"],
  ["dr-ashish-gupta-0",["Ghaziabad"],"Current practice FAQ: Vaishali"],
  ["dr-ashutosh-shukla",["Gurugram"],"Current practice FAQ: Gurgaon"],
  ["dr-atul-bhasin",["New Delhi"],"Current practice FAQ: BLK Max"],
  ["dr-atul-somani",["Nagpur"],"Current practice FAQ: Nagpur"],
  ["dr-avinash-s",["New Delhi"],"Current practice FAQ: BLK Max"],
  ["dr-ayachi-bajpai",["New Delhi"],"Current practice FAQ: Max Smart Saket"],
  ["dr-b-d-sharma",["New Delhi"],"Current practice FAQ: Patparganj"],
  ["dr-bhanu-pratap-singh",["Bathinda"],"Current practice FAQ: Bathinda"],
  ["dr-pawan-goel",["New Delhi"],"Current practice FAQ: Max Shalimar Bagh"],
  ["dr-rm-chhabra",["New Delhi"],"Current practice FAQ: Max Shalimar Bagh"],
  ["dr-rutuja-atul-tambe",["New Delhi","Gurugram"],"Current practice FAQ: Max Saket and Gurgaon"],
  ["dr-rutuja-rajendraprakash-sharma",["New Delhi"],"Current practice FAQ: Max Max Smart Saket"],
  ["dr-sanjay-raina",["New Delhi"],"Current practice FAQ: Max Shalimar Bagh"],
  ["dr-shama-mahendru",["New Delhi"],"Current practice FAQ: Max Saket"],
  ["dr-surya-kant-mathur",["Mohali"],"Current practice FAQ: Max Mohali"],
  ["dr-sushil-gupta",["Lucknow"],"Current practice FAQ: Max Lucknow"],
  ["dr-swati-chopra",["Dehradun"],"Current practice FAQ: Max Dehradun"],
  ["dr-swati-pandit",["New Delhi"],"Current practice FAQ: Max Max Smart Saket"],
  ["dr-tanvi-umashree",["Gurugram"],"Current practice FAQ: Max Gurugram"],
  ["dr-vaibhav-singhal",["Ghaziabad"],"Current practice FAQ: Max Vaishali"],
  ["dr-vimal-upreti",["Noida"],"Current practice FAQ: Max Noida"],
  ["dr-vineet-arora",["New Delhi"],"Current practice FAQ: Max Shalimar Bagh, New Delhi"],
  ["dr-maj-anil-kumar-awasthi",["Lucknow"],"Current practice FAQ: Max Lucknow"],
  ["dr-a-zeenat-ahmed",["Noida"],"Current practice FAQ: Max Noida"],
  ["dr-shashank-srivastava",["New Delhi"],"Current practice FAQ: Max Patparganj"],
  ["dr-viveka-kumar",["New Delhi"],"Current practice FAQ: Max Saket and Max Smart Saket"],
  ["dr-yogendra-singh",["Dehradun"],"Current practice FAQ: Max Dehradun"],
  ["dr-aditya-dutta",["New Delhi"],"Current practice FAQ: Max Saket"],
  ["dr-alok-joshi",["New Delhi"],"Current practice FAQ: Max Shalimar Bagh"],
  ["dr-aprajita-pradhan",["New Delhi"],"Current practice FAQ: Max Dwarka"],
  ["dr-emmy-grewal",["Mohali"],"Current practice FAQ: Max Mohali"],
  ["dr-hemi-soneja",["Gurugram"],"Current practice FAQ: Max Gurgaon"],
  ["dr-khalid-j-farooqui",["New Delhi","Gurugram"],"Current practice FAQ: Max Max Smart Saket and Gurgaon"],
  ["dr-mahesh-rath",["Bhubaneswar"],"Current practice FAQ: Max Bhubaneswar"],
  ["dr-niti-aggarwal",["New Delhi"],"Current practice FAQ: Max Patparganj"],
  ["dr-nupoor-vaghasia",["New Delhi"],"Current practice FAQ: Max Max Smart Saket"],
  ["dr-pankaj-aneja",["New Delhi"],"Current practice FAQ: Max Shalimar Bagh"],
  ['dr-sudipta-acharya', ['Bhubaneswar'], 'Practice FAQ: Max Super Speciality Hospital, Bhubaneswar'],
  ['dr-sujeet-narain', ['Noida'], 'Practice FAQ: Max Super Speciality Hospital, Noida'],
  ['dr-sumeet-sethi', ['New Delhi'], 'Practice FAQ: Max Super Speciality Hospital, Saket'],
  ['dr-sunil-kumar-agarwal', ['New Delhi'], 'Practice FAQ: Max Super Speciality Hospital, Saket'],
  ['dr-sunil-kumar-wadhwa', ['Gurugram'], 'Practice FAQ: Max Hospital, Gurgaon'],
  ['dr-susanta-shaila', ['Bhubaneswar'], 'Practice FAQ: Max Super Speciality Hospital, Bhubaneswar'],
  ['dr-vijay-kumar-chopra', ['New Delhi'], 'Practice FAQ: Max Super Speciality Hospital, Saket'],
  ['dr-nitish-rai-1', ['New Delhi'], 'Practice FAQ: Max Super Speciality Hospital, Patparganj'],
  ['dr-preeti-sharma', ['Dehradun'], 'Practice FAQ: Max Super Speciality Hospital, Dehradun'],
  ['dr-rajeev-rathi', ['New Delhi'], 'Practice FAQ: Max Super Speciality Hospital, Saket'],
  ['dr-rajendra-kumar-agarwal', ['New Delhi'], 'Practice FAQ: Max Smart Saket and Panchsheel Park'],
  ['dr-rajiv-agarwal', ['New Delhi'], 'Practice FAQ: Max Super Speciality Hospital, Saket'],
  ['dr-rakesh-sharma', ['Mohali'], 'Practice FAQ: Max Super Speciality Hospital, Mohali'],
  ['dr-ravi-kumar-singh', ['Dehradun'], 'Practice FAQ: Max Super Speciality Hospital, Dehradun'],
  ['dr-rohit-goel', ['Gurugram'], 'Practice FAQ: Max Hospital, Gurgaon'],
  ['dr-roopa-salwan', ['New Delhi'], 'Practice FAQ: Max Super Speciality Hospital, Saket'],
  ['dr-sabyasachi-rout', ['Bhubaneswar'], 'Practice FAQ: Max Super Speciality Hospital, Bhubaneswar'],
  ['dr-sajal-gupta', ['Ghaziabad', 'Noida'], 'Practice FAQ: Max Vaishali and Max Multi Speciality Centre, Noida'],
  ['dr-sameer-pagad', ['Mumbai'], 'Practice FAQ: Nanavati Max Super Speciality Hospital, Mumbai'],
  ['dr-sameer-shrivastava', ['New Delhi'], 'Practice FAQ: Max Saket and BLK-Max, New Delhi'],
  ['dr-gagandip-singh', ['Mohali'], 'Practice FAQ: Max Super Speciality Hospital, Mohali'],
  ['dr-gaurav-bhardwaj-1', ['Noida'], 'Practice FAQ: Max Multi Speciality Centre, Sector 19, Noida'],
  ['dr-gaurav-minocha', ['Ghaziabad'], 'Practice FAQ: Max Super Speciality Hospital, Vaishali'],
  ['dr-heemanshu-lodhi', ['Ghaziabad'], 'Practice FAQ: Max Super Speciality Hospital, Vaishali'],
  ['dr-kamlesh-raut', ['New Delhi'], 'Practice FAQ: Max Superspeciality Hospital, Dwarka'],
  ['dr-kapil-k-chattree', ['Mohali'], 'Practice FAQ: Max Super Specialty Hospital, Mohali'],
  ['dr-manoj-kumar-0', ['New Delhi'], 'Practice FAQ: Max Super Speciality Hospital, Patparganj'],
  ['dr-mitendra-singh-yadav', ['New Delhi'], 'Practice FAQ: Max Multi Speciality Centre, Panchsheel Park'],
  ['dr-mithilesh-kumar', ['New Delhi'], 'Practice FAQ: Max Super Speciality Hospital, Patparganj'],
  ['dr-mohan-bhargava', ['New Delhi'], 'Practice FAQ: Max Super Speciality Hospital, Saket'],
  ['dr-mukesh-jaiswal', ['Lucknow'], 'Practice FAQ: Max Super Specialty Hospital, Lucknow'],
  ['dr-mukul-bhargava', ['Gurugram'], 'Practice FAQ: Max Hospital, Gurgaon'],
  ['dr-nakul-sinha', ['Lucknow'], 'Practice FAQ: Max Super Speciality Hospital, Lucknow'],
  ['akhilesh-shrivastava', ['New Delhi'], 'Appointment selector: Saket East, Saket West and Panchsheel Park'],
  ['dr-ambukeshwar-singh', ['Lucknow'], 'Practice FAQ: Max Super Speciality Hospital, Lucknow'],
  ['dr-amit-pendharkar', ['New Delhi'], 'Appointment location and practice FAQ: Max Super Speciality Hospital, Dwarka'],
  ['dr-amitesh-ranjan', ['Lucknow'], 'Practice FAQ: Max Super Speciality Hospital, Lucknow'],
  ['dr-anupam-goel', ['New Delhi'], 'Practice FAQ: Max Super Speciality Hospital, Saket'],
  ['dr-arun-kumar-gupta', ['Gurugram'], 'Practice FAQ: Max Hospital, Gurgaon'],
  ['dr-arvind-m-das', ['New Delhi', 'Gurugram'], 'Practice FAQ and consultation schedules: Panchsheel Park, Saket and Gurgaon'],
  ['dr-ashish-agarwal', ['New Delhi'], 'Practice FAQ: Max Super Speciality Hospital, Dwarka'],
  ['dr-balbir-singh', ['New Delhi'], 'Practice FAQ: Saket and Patparganj'],
  ['dr-bipin-kumar-dubey', ['New Delhi'], 'Practice FAQ: Max Super Speciality Hospital, Dwarka'],
  ['dr-col-cproy', ['New Delhi'], 'Practice FAQ: Max Smart and Max Super Speciality Hospitals, Saket'],
  ['dr-chayan-vermani', ['New Delhi'], 'Practice FAQ: Max Super Speciality Hospital, Patparganj'],
  ['dr-danish-hasan-kazmi', ['Lucknow'], 'Practice FAQ: Max Super Speciality Hospital, Lucknow'],
  ['dr-dixit-goyal', ['Bathinda'], 'Practice FAQ: Max Super Speciality Hospital, Bathinda']
];
export const individualLocationReviews = maxReviews.map(([slug, locations, reported, sourceUrl]) => ({
  profileUrl: `https://www.maxhealthcare.in/doctor/${slug}`,
  ...(sourceUrl?{sourceUrl}:{}),
  locations, reported, checkedAt: '2026-10-01', locator: reported,
  identityBasis: 'Institutional doctor profile or named directory entry; matching name and clinical role'
}));
Object.assign(individualLocationReviews.find(r => r.profileUrl.endsWith('/dr-priyamvada-tyagi')), {
  supportingSourceUrls: ['https://sushruthealthcare.in/']
});
Object.assign(individualLocationReviews.find(r => r.profileUrl.endsWith('/dr-s-k-das')), {
  sourceIssues: ['Individual profile work-experience paragraph names a different doctor; location established independently from the named directory card.']
});
Object.assign(individualLocationReviews.find(r => r.profileUrl.endsWith('/dr-prem-narayan-vaish')), {
  identityBasis: 'Named physician clinic page; matching full name, qualification and hospital',
  reviewMethod: 'PUBLIC_CLINIC_LOCATION_REVIEWED'
});
individualLocationReviews.push({
  profileUrl: 'https://www.medanta.org/hospitals-near-me/south-delhi/speciality/internal-medicine/doctor/dr-neelam-bisht',
  locations: ['New Delhi'], reported: 'Medanta Mediclinic, Defence Colony, South Delhi',
  checkedAt: '2026-10-01', locator: 'Doctor page title and South Delhi branch URL, joined to official clinic page',
  supportingSourceUrls: ['https://www.medanta.org/hospitals-near-me/gurugram-hospital/south-delhi']
});
