// Curated discovery observations; never substitute discovery counts for HCP counts.
export const sourceLibrary = [
  {id:"nk-linkedin-congress",platform:"LinkedIn",kind:"Post",hcpId:"kol-nitin-kapoor",relationship:"Authored",person:"Nitin Kapoor",title:"ESI Obesity Week: evolving understanding of obesity",url:"https://www.linkedin.com/posts/nitin-kapoor-endocrine_endocrinesocietyofindia-esiobesityweek-activity-7436039629100744704-n21H",publishedAt:null,summary:"Kapoor discusses Donna Ryan's congress presentation. Indexed hashtags include #EndocrineSocietyofIndia and #ESIObesityWeek.",status:"Indexed public record",topics:["Obesity","Congress discussion"],type:"SOCIAL"},
  {id:"nk-linkedin-editor",platform:"LinkedIn",kind:"Post",hcpId:"kol-nitin-kapoor",relationship:"Institutional mention",person:"Nitin Kapoor",title:"Endocrine Connections announces Senior Editor in Obesity",url:"https://www.linkedin.com/posts/endocrineconnections_we-would-like-to-welcome-a-new-senior-editor-activity-7407405452021432320-OLRz",publishedAt:null,summary:"The journal names Kapoor and CMC Vellore in its editorial appointment announcement. This is a journal post, not a post authored by Kapoor.",status:"Indexed public record",topics:["Editorial leadership","Obesity"],type:"SOCIAL"},
  {id:"sk-podcast-mind",platform:"Podcasts",kind:"Episode",hcpId:"kol-sanjay-kalra",relationship:"Speaker",person:"Sanjay Kalra; Vaishali Deshmukh",title:"Mind-Body Medicine in Diabetes Management",url:"https://pmc.ncbi.nlm.nih.gov/articles/PMC9417074/",publishedAt:"2022-08-26",summary:"Publisher transcript identifies Kalra at Bharti Hospital, Karnal, and Deshmukh at Deenanath Mangeshkar Hospital, Pune. Audio is linked by the article. Deshmukh is not yet a separately verified platform dossier.",status:"Public transcript",topics:["Diabetes","Mind-body medicine"],type:"PODCAST"},
  {id:"sk-podcast-language",platform:"Podcasts",kind:"Episode",hcpId:"kol-sanjay-kalra",relationship:"Speaker",person:"Sanjay Kalra; Partha Kar",title:"Language Matters in Diabetes",url:"https://link.springer.com/article/10.1007/s13300-021-01069-z",publishedAt:null,summary:"Publisher-hosted podcast conversation on diabetes communication. Kar identifies his practice in Portsmouth, UK; he is not counted as an India-practising HCP.",status:"Public transcript",topics:["Diabetes","Clinical communication"],type:"PODCAST"},
  {id:"sk-podcast-abbott",platform:"Podcasts",kind:"Episode",hcpId:"kol-sanjay-kalra",relationship:"Speaker",person:"Sanjay Kalra",title:"Diabetes Management As We Know It",url:"https://podcasts.apple.com/in/podcast/diabetes-management-as-we-know-it/id1657973708?i=1000589278597",publishedAt:"2022-12-07",summary:"29-minute episode with Kalra, Prashant Subramanian and Nupur Lalvani. Presented by Abbott; retain commercial context when interpreting opinions.",status:"Public episode metadata",sponsorship:"Presented by Abbott",topics:["Diabetes technology","Patient education"],type:"PODCAST"},
  {id:"jdc-newsletter",platform:"Medical blogs",kind:"Newsletter",hcpId:null,relationship:"Editor",person:"Jothydev Kesavadev",title:"JDC Diabetes Gems",url:"https://jothydev.com/newsletter/",publishedAt:null,summary:"Open diabetes newsletter identifies Kesavadev as chief editor and its Kerala diabetes centres. An editorial role is not authorship of every article. Separate HCP dossier review is pending.",status:"Source discovered; dossier pending",topics:["Diabetes research","Clinical synthesis"],type:"BLOG"},
  {id:"pal-substack",platform:"Substack",kind:"Article",hcpId:null,relationship:"Authored",person:"Pal Manickam",title:"Could you be Diabetic without knowing it?",url:"https://drpalsnewme.substack.com/p/could-you-be-diabetic-without-knowing",publishedAt:"2025-04-04",summary:"Named-author diabetes education newsletter relevant to Indian audiences. Practice geography and specialist scope have not been verified for inclusion in the India HCP denominator.",status:"Discovery only; scope review",topics:["Diabetes education"],type:"NEWSLETTER"},
  {id:"mohan-blog",platform:"Medical blogs",kind:"Article",hcpId:"kol-v-mohan",relationship:"Mentioned",person:"V Mohan",title:"Dr. Mohan's - A Home Away from Home",url:"https://drmohans.com/dr-mohans-a-home-away-from-home/",publishedAt:"2020-08-31",summary:"Institution-hosted Sugar and Spice article by Swati Amar mentions V Mohan and Rema Mohan. It must not be attributed to V Mohan as author.",status:"Public article",topics:["Type 1 diabetes","Patient experience"],type:"BLOG"},
  {id:"sk-x-watch",platform:"X",kind:"Account watch",hcpId:"kol-sanjay-kalra",relationship:"Account reference",person:"Sanjay Kalra",title:"@SanjayKalraDr1",url:"https://x.com/SanjayKalraDr1",publishedAt:null,summary:"The podcast episode description explicitly links this handle to Kalra. Current ownership and post activity require rechecking; no X posts or metrics captured in this search.",status:"Watch target; current account review",evidenceUrl:"https://podcasts.apple.com/in/podcast/diabetes-management-as-we-know-it/id1657973708?i=1000589278597",topics:["Diabetes","Endocrinology"],type:"SOCIAL"}
].map(record=>({...record,observedOn:"2026-09-28",collectionMode:"MANUAL_WEB_DISCOVERY",metrics:null}));

export const congressWatches = [
  {name:"ESI Obesity Week",query:"#ESIObesityWeek",status:"Hashtag observed on LinkedIn; X activity unverified",evidenceUrl:sourceLibrary[0].url},
  {name:"RSSDI 2026",query:'"RSSDI2026" OR "RSSDI 2026"',status:"Proposed X search; not a verified official hashtag",evidenceUrl:"https://www.rssdibengaluru2026.com/"},
  {name:"ESICON 2026",query:'"ESICON2026" OR "ESICON 2026"',status:"Proposed X search; not a verified official hashtag",evidenceUrl:"https://www.esicon2026.com/scientific_programme.php"}
];

export function attachDiscoveredFootprints(people) {
  for (const record of sourceLibrary) {
    if (!record.hcpId || record.kind === "Account watch") continue;
    const person=people.find(person=>person.id===record.hcpId);
    if (!person || person.footprints.some(item=>item.url===record.url)) continue;
    person.footprints.push({id:record.id,type:record.type,title:record.title,summary:record.summary,publisher:record.platform,date:record.publishedAt||"Publication date unconfirmed",confidence:"REVIEW",url:record.url,relationship:record.relationship,observedOn:record.observedOn});
  }
  return people;
}
